"""
Part 2: Maintenance, Indian, Japanese, Chinese recipes
"""
import json
from pathlib import Path

def recipe(id, name, cuisine, tags, diet, diff, time, req_ing, opt_ing, cookware, steps, mistakes, cal, prot, carbs, fats, servings=2, impact=None):
    r = {"id": id, "name": name, "cuisine": cuisine, "category": "food", "fitness_tags": tags, "diet": diet, "difficulty": diff, "time_minutes": time, "required_ingredients": req_ing, "optional_ingredients": opt_ing, "cookware": cookware, "steps": steps, "common_mistakes": mistakes, "nutrition": {"calories": cal, "protein_g": prot, "carbs_g": carbs, "fats_g": fats}, "servings": servings}
    if impact: r["cooking_impact"] = impact
    return r

# ============ MAINTENANCE (25) ============
maintenance = [
    recipe("mt-balanced-bowl", "Balanced Buddha Bowl", "Global", ["maintenance", "balanced"], "veg", "Easy", 25, ["quinoa", "chickpeas", "avocado", "cucumber", "tahini"], ["tomato", "lemon"], ["pot", "bowl"], ["Cook quinoa", "Drain chickpeas", "Dice vegetables", "Assemble bowl", "Drizzle tahini"], ["Dry quinoa = wrong ratio", "Brown avocado = oxidized"], 400, 15, 45, 18),
    recipe("mt-stir-fry-tofu", "Everyday Tofu Stir Fry", "Asian", ["maintenance"], "veg", "Easy", 20, ["tofu", "mixed vegetables", "soy sauce", "garlic", "oil"], ["ginger", "sesame"], ["wok", "spatula"], ["Press and cube tofu", "Fry tofu until golden", "Stir-fry vegetables", "Add sauce", "Combine all"], ["Soft tofu = not pressed", "Crowded wok = steaming"], 320, 18, 25, 16),
    recipe("mt-pasta-veggies", "Simple Pasta Primavera", "Italian", ["maintenance"], "veg", "Easy", 25, ["pasta", "zucchini", "cherry tomatoes", "olive oil", "garlic"], ["parmesan", "basil"], ["pot", "pan"], ["Cook pasta al dente", "Saute vegetables", "Combine pasta and veggies", "Add olive oil", "Top with cheese"], ["Overcooked pasta", "Too little oil"], 380, 12, 55, 12),
    recipe("mt-rice-beans", "Mexican Rice and Beans", "Mexican", ["maintenance", "high_fiber"], "veg", "Easy", 25, ["rice", "black beans", "corn", "tomato", "cumin"], ["cilantro", "lime"], ["pot", "pan"], ["Cook rice with tomato", "Heat beans with cumin", "Add corn", "Mix all together", "Garnish with cilantro"], ["Mushy rice", "Bland beans"], 350, 12, 58, 6),
    recipe("mt-salmon-salad", "Light Salmon Salad", "Global", ["maintenance", "omega3"], "non-veg", "Easy", 20, ["salmon", "mixed greens", "olive oil", "lemon", "dill"], ["capers", "onion"], ["pan", "bowl"], ["Season salmon", "Pan-fry 4 min per side", "Prepare greens", "Flake salmon on salad", "Dress with lemon oil"], ["Overcooked salmon", "Undressed salad"], 380, 30, 8, 25),
    recipe("mt-veggie-wrap", "Mediterranean Veggie Wrap", "Mediterranean", ["maintenance"], "veg", "Easy", 15, ["wrap", "hummus", "cucumber", "tomato", "feta"], ["olives", "lettuce"], ["plate"], ["Spread hummus on wrap", "Add vegetables", "Crumble feta", "Roll tightly", "Cut in half"], ["Overfilled wrap", "Dry wrap"], 320, 10, 35, 15),
    recipe("mt-chicken-pasta", "Creamy Chicken Pasta", "Italian", ["maintenance"], "non-veg", "Medium", 30, ["pasta", "chicken breast", "cream", "garlic", "parmesan"], ["spinach", "mushrooms"], ["pot", "pan"], ["Cook pasta", "Slice and cook chicken", "Make cream sauce", "Combine all", "Add cheese"], ["Sauce too thick", "Dry chicken"], 480, 28, 50, 20),
    recipe("mt-fried-rice", "Classic Egg Fried Rice", "Chinese", ["maintenance"], "egg", "Easy", 15, ["day-old rice", "eggs", "peas", "soy sauce", "oil"], ["green onion", "carrot"], ["wok", "spatula"], ["Heat wok high", "Scramble eggs aside", "Fry rice 3 min", "Add vegetables", "Mix with eggs"], ["Wet fresh rice", "Low heat"], 350, 12, 50, 12),
    recipe("mt-fish-tacos", "Easy Fish Tacos", "Mexican", ["maintenance"], "non-veg", "Easy", 20, ["white fish", "corn tortillas", "cabbage", "lime", "sour cream"], ["cilantro", "salsa"], ["pan", "bowl"], ["Season and cook fish", "Warm tortillas", "Shred cabbage", "Assemble tacos", "Add toppings"], ["Overcooked fish", "Cold tortillas"], 380, 25, 35, 15),
    recipe("mt-soup-bread", "Hearty Soup with Bread", "Global", ["maintenance"], "veg", "Easy", 35, ["vegetable broth", "potato", "carrot", "onion", "crusty bread"], ["celery", "herbs"], ["pot", "knife"], ["Dice vegetables", "Saute onion", "Add broth and veggies", "Simmer 25 min", "Serve with bread"], ["Unevenly cut veggies", "Too little broth"], 320, 8, 50, 8),
    recipe("mt-grilled-chicken", "Herb Grilled Chicken", "Global", ["maintenance"], "non-veg", "Easy", 25, ["chicken thighs", "olive oil", "Italian herbs", "garlic", "lemon"], ["rosemary"], ["grill pan"], ["Marinate chicken 30 min", "Grill 7 min per side", "Rest 5 min", "Squeeze lemon", "Serve"], ["Not marinating", "Overcooked"], 350, 30, 5, 22),
    recipe("mt-quinoa-salad", "Fresh Quinoa Salad", "Global", ["maintenance"], "veg", "Easy", 20, ["quinoa", "cucumber", "tomato", "lemon", "olive oil"], ["mint", "feta"], ["pot", "bowl"], ["Cook quinoa and cool", "Dice vegetables", "Mix together", "Dress with lemon oil", "Serve cold"], ["Hot quinoa wilts veggies", "Overdressed"], 280, 10, 38, 10),
    recipe("mt-shakshuka", "Simple Shakshuka", "Middle Eastern", ["maintenance"], "egg", "Easy", 25, ["eggs", "tomatoes", "onion", "bell pepper", "cumin"], ["feta", "cilantro"], ["pan", "lid"], ["Saute onion and pepper", "Add tomatoes and spices", "Simmer 10 min", "Create wells for eggs", "Cover and cook eggs"], ["Overcooked eggs", "Thin sauce"], 280, 14, 18, 16),
    recipe("mt-teriyaki-bowl", "Teriyaki Chicken Bowl", "Japanese", ["maintenance"], "non-veg", "Easy", 25, ["chicken thigh", "rice", "broccoli", "teriyaki sauce", "sesame"], ["edamame"], ["pan", "pot"], ["Cook rice", "Cook chicken with sauce", "Steam broccoli", "Assemble bowl", "Top with sesame"], ["Dry chicken", "Overcooked broccoli"], 420, 28, 48, 14),
    recipe("mt-omelette-veg", "Garden Vegetable Omelette", "Global", ["maintenance"], "egg", "Easy", 12, ["eggs", "bell pepper", "onion", "cheese", "butter"], ["herbs"], ["pan", "spatula"], ["Beat eggs", "Saute vegetables", "Pour eggs", "Add cheese", "Fold and serve"], ["Overcooked eggs", "High heat"], 280, 16, 6, 20),
    recipe("mt-noodle-soup", "Asian Noodle Soup", "Asian", ["maintenance"], "veg", "Easy", 20, ["noodles", "vegetable broth", "bok choy", "tofu", "soy sauce"], ["ginger", "scallion"], ["pot"], ["Bring broth to boil", "Cook noodles", "Add tofu and bok choy", "Season with soy sauce", "Serve hot"], ["Overcooked noodles", "Bland broth"], 300, 14, 40, 8),
    recipe("mt-pizza-toast", "Easy Pizza Toast", "Italian", ["maintenance"], "veg", "Easy", 15, ["bread", "tomato sauce", "mozzarella", "olive oil", "oregano"], ["bell pepper", "olives"], ["oven", "baking sheet"], ["Toast bread lightly", "Spread sauce", "Add cheese and toppings", "Bake at 200C for 8 min", "Serve hot"], ["Soggy bread", "Too much sauce"], 320, 12, 35, 14),
    recipe("mt-greek-salad", "Classic Greek Salad", "Greek", ["maintenance"], "veg", "Easy", 10, ["cucumber", "tomato", "red onion", "feta", "olives"], ["olive oil", "oregano"], ["bowl", "knife"], ["Chop vegetables", "Add olives", "Crumble feta on top", "Drizzle olive oil", "Sprinkle oregano"], ["Watery tomatoes", "Too much feta"], 220, 8, 12, 16),
    recipe("mt-burrito", "Quick Bean Burrito", "Mexican", ["maintenance", "high_fiber"], "veg", "Easy", 15, ["flour tortilla", "refried beans", "rice", "cheese", "salsa"], ["sour cream", "lettuce"], ["microwave", "plate"], ["Warm tortilla", "Spread beans", "Add rice and cheese", "Add toppings", "Roll tightly"], ["Cold beans", "Tearing tortilla"], 420, 14, 55, 16),
    recipe("mt-poke-bowl", "Simple Poke Bowl", "Hawaiian", ["maintenance", "omega3"], "non-veg", "Easy", 20, ["sushi rice", "fresh tuna", "avocado", "soy sauce", "sesame"], ["cucumber", "seaweed"], ["pot", "bowl"], ["Cook sushi rice", "Cube fresh tuna", "Slice avocado", "Assemble bowl", "Drizzle soy and sesame"], ["Old fish", "Warm fish"], 400, 28, 42, 14),
    recipe("mt-veggie-curry", "Easy Vegetable Curry", "Indian", ["maintenance"], "veg", "Easy", 30, ["mixed vegetables", "coconut milk", "curry powder", "onion", "garlic"], ["ginger", "cilantro"], ["pot", "pan"], ["Saute onion and garlic", "Add curry powder", "Add vegetables", "Pour coconut milk", "Simmer 15 min"], ["Burnt spices", "Watery curry"], 280, 6, 25, 18),
    recipe("mt-club-sandwich", "Classic Club Sandwich", "American", ["maintenance"], "non-veg", "Easy", 15, ["bread", "turkey", "bacon", "lettuce", "tomato"], ["mayo", "cheese"], ["toaster", "pan"], ["Toast bread", "Cook bacon", "Layer ingredients", "Cut diagonally", "Secure with picks"], ["Soggy bread", "Too thick to eat"], 450, 28, 35, 22),
    recipe("mt-naan-curry", "Dal with Naan", "Indian", ["maintenance", "vegetarian"], "veg", "Easy", 30, ["red lentils", "onion", "garlic", "garam masala", "naan"], ["tomato", "cilantro"], ["pot", "pan"], ["Cook lentils until soft", "Make tempering with spices", "Combine dal and tempering", "Warm naan", "Serve together"], ["Undercooked lentils", "Burnt tempering"], 380, 16, 55, 8),
    recipe("mt-steak-salad", "Steak Salad", "American", ["maintenance", "high_protein"], "non-veg", "Medium", 25, ["sirloin steak", "mixed greens", "blue cheese", "cherry tomatoes", "balsamic"], ["red onion"], ["grill pan", "bowl"], ["Cook steak to preference", "Rest and slice", "Prepare salad", "Top with steak", "Drizzle dressing"], ["Overcooked steak", "Warm salad"], 420, 32, 12, 26),
    recipe("mt-ramen", "Simple Ramen Bowl", "Japanese", ["maintenance"], "egg", "Medium", 25, ["ramen noodles", "chicken broth", "soft boiled egg", "nori", "green onion"], ["corn", "butter"], ["pot"], ["Make soft boiled egg", "Heat broth", "Cook noodles", "Assemble bowl", "Add toppings"], ["Overcooked egg", "Overcooked noodles"], 380, 18, 42, 15),
]

# ============ INDIAN (25) ============
indian = [
    recipe("in-butter-chicken", "Butter Chicken", "Indian", ["maintenance"], "non-veg", "Medium", 40, ["chicken", "tomato puree", "cream", "butter", "garam masala"], ["kasuri methi", "ginger"], ["pan", "pot"], ["Marinate chicken in yogurt", "Cook chicken", "Make tomato gravy", "Add cream and butter", "Simmer with chicken"], ["Separated cream", "Too acidic"], 450, 32, 15, 28),
    recipe("in-palak-paneer", "Palak Paneer", "Indian", ["vegetarian", "high_protein"], "veg", "Medium", 30, ["paneer", "spinach", "onion", "garlic", "cream"], ["garam masala", "cumin"], ["pot", "blender"], ["Blanch spinach and blend", "Saute onion and garlic", "Add spinach puree", "Add paneer cubes", "Finish with cream"], ["Bitter spinach from overcooking", "Hard paneer"], 350, 20, 12, 26),
    recipe("in-chole", "Punjabi Chole", "Indian", ["high_protein", "high_fiber"], "veg", "Medium", 35, ["chickpeas", "onion", "tomato", "chole masala", "ginger"], ["tamarind", "tea bags"], ["pressure cooker", "pan"], ["Soak and cook chickpeas", "Make onion tomato gravy", "Add spices and chickpeas", "Simmer 15 min", "Serve with bhatura"], ["Undercooked chickpeas", "Bland masala"], 280, 12, 38, 8),
    recipe("in-dal-tadka", "Dal Tadka", "Indian", ["high_protein", "vegetarian"], "veg", "Easy", 30, ["yellow dal", "onion", "tomato", "cumin", "ghee"], ["garlic", "red chili"], ["pot", "small pan"], ["Cook dal with turmeric", "Make tadka with ghee and cumin", "Saute onion tomato", "Add dal", "Pour tadka on top"], ["Too thick dal", "Burnt tadka"], 200, 12, 28, 6),
    recipe("in-aloo-gobi", "Aloo Gobi", "Indian", ["vegetarian"], "veg", "Easy", 25, ["potato", "cauliflower", "onion", "turmeric", "cumin"], ["ginger", "coriander"], ["pan", "lid"], ["Cut vegetables into pieces", "Saute cumin in oil", "Add onion and potatoes", "Add cauliflower", "Cover and cook 15 min"], ["Mushy vegetables", "Too much water"], 180, 5, 28, 6),
    recipe("in-chicken-biryani", "Chicken Biryani", "Indian", ["high_protein"], "non-veg", "Hard", 60, ["chicken", "basmati rice", "yogurt", "biryani masala", "onion"], ["saffron", "mint"], ["pot", "heavy pan"], ["Marinate chicken", "Par-cook rice", "Layer chicken and rice", "Dum cook 20 min", "Serve with raita"], ["Overcooked rice", "Dry chicken"], 520, 30, 55, 20),
    recipe("in-samosa", "Crispy Samosas", "Indian", ["snack"], "veg", "Hard", 45, ["potato", "peas", "cumin", "flour", "oil"], ["green chili", "coriander"], ["pot", "rolling pin"], ["Make and rest dough", "Make spiced potato filling", "Shape samosas", "Deep fry until golden", "Serve with chutney"], ["Leaking samosas", "Soggy samosas"], 250, 4, 32, 12, 4),
    recipe("in-paneer-tikka-m", "Paneer Tikka Masala", "Indian", ["high_protein", "vegetarian"], "veg", "Medium", 35, ["paneer", "tomato", "cream", "kashmiri chili", "kasuri methi"], ["ginger", "garlic"], ["pan", "oven"], ["Make tikka spice paste", "Grill paneer cubes", "Make tomato gravy", "Add paneer to gravy", "Finish with cream"], ["Overcooked paneer", "Too much cream"], 380, 22, 14, 28),
    recipe("in-rajma", "Rajma Chawal", "Indian", ["high_protein", "high_fiber"], "veg", "Medium", 40, ["kidney beans", "tomato", "onion", "garam masala", "rice"], ["kashmiri chili"], ["pressure cooker", "pan"], ["Soak and cook rajma", "Make onion tomato gravy", "Add beans and simmer", "Cook rice separately", "Serve together"], ["Hard beans", "Bland gravy"], 350, 15, 55, 6),
    recipe("in-chicken-curry", "Home Style Chicken Curry", "Indian", ["high_protein"], "non-veg", "Medium", 40, ["chicken", "onion", "tomato", "ginger", "garlic"], ["coriander", "garam masala"], ["pot"], ["Make ginger garlic paste", "Cook onion until golden", "Add tomato and spices", "Add chicken and cook", "Simmer until done"], ["Raw masala taste", "Tough chicken"], 380, 32, 10, 22),
    recipe("in-dosa", "Crispy Masala Dosa", "Indian", ["vegetarian"], "veg", "Medium", 30, ["dosa batter", "potato", "onion", "mustard seeds", "curry leaves"], ["green chili"], ["tawa", "pan"], ["Make potato masala", "Heat tawa well", "Spread batter thin", "Add oil and cook until crispy", "Add filling and fold"], ["Not crispy", "Thick spreading"], 280, 8, 45, 8),
    recipe("in-korma", "Vegetable Korma", "Indian", ["vegetarian"], "veg", "Medium", 35, ["mixed vegetables", "cashews", "cream", "onion", "cardamom"], ["bay leaf", "cinnamon"], ["blender", "pot"], ["Make cashew paste", "Saute onion with whole spices", "Add vegetables", "Add cashew paste and cream", "Simmer 15 min"], ["Grainy cashew paste", "Watery korma"], 320, 8, 25, 22),
    recipe("in-idli-sambar", "Idli with Sambar", "Indian", ["vegetarian", "low_fat"], "veg", "Medium", 35, ["idli batter", "toor dal", "sambar powder", "vegetables", "tamarind"], ["mustard seeds"], ["idli steamer", "pot"], ["Steam idlis 12 min", "Cook dal", "Add vegetables and tamarind", "Make sambar", "Serve with coconut chutney"], ["Hard idli", "Sour sambar"], 250, 10, 42, 4, 4),
    recipe("in-pulao", "Vegetable Pulao", "Indian", ["vegetarian"], "veg", "Easy", 30, ["basmati rice", "mixed vegetables", "cumin", "bay leaf", "ghee"], ["cloves", "cinnamon"], ["pot"], ["Saute whole spices in ghee", "Add vegetables and rice", "Add water 1:1.5 ratio", "Cook covered 15 min", "Fluff and serve"], ["Mushy rice", "Undercooked veggies"], 280, 6, 48, 8),
    recipe("in-poha", "Kanda Poha", "Indian", ["breakfast"], "veg", "Easy", 15, ["poha", "onion", "potato", "peanuts", "mustard seeds"], ["curry leaves", "turmeric"], ["pan"], ["Wash and drain poha", "Fry peanuts and potatoes", "Add mustard seeds and onion", "Add poha and turmeric", "Mix and serve with lemon"], ["Soggy poha", "Too dry"], 220, 5, 35, 8),
    recipe("in-upma", "Rava Upma", "Indian", ["breakfast"], "veg", "Easy", 20, ["semolina", "onion", "ginger", "curry leaves", "mustard seeds"], ["green peas", "carrot"], ["pan", "pot"], ["Roast semolina until fragrant", "Make tempering", "Add vegetables and water", "Add semolina gradually", "Cook until done"], ["Lumpy upma", "Too thick or thin"], 200, 5, 32, 6),
    recipe("in-malai-kofta", "Malai Kofta", "Indian", ["vegetarian"], "veg", "Hard", 45, ["paneer", "potato", "cashews", "cream", "tomato"], ["kashmiri chili"], ["pot", "fryer"], ["Make paneer potato koftas", "Deep fry until golden", "Make cashew tomato gravy", "Add cream", "Add koftas before serving"], ["Hard koftas", "Broken koftas"], 450, 15, 25, 32),
    recipe("in-roti-sabzi", "Roti with Mixed Sabzi", "Indian", ["balanced"], "veg", "Easy", 30, ["wheat flour", "mixed vegetables", "onion", "tomato", "spices"], ["ghee"], ["tawa", "pan"], ["Knead and rest dough", "Make vegetable curry", "Roll and cook rotis", "Apply ghee", "Serve together"], ["Hard roti", "Bland sabzi"], 320, 10, 48, 8, 3),
    recipe("in-chana-masala", "Chana Masala", "Indian", ["high_protein", "high_fiber"], "veg", "Easy", 25, ["chickpeas", "onion", "tomato", "chana masala", "ginger"], ["amchur", "coriander"], ["pan"], ["Saute onion until golden", "Add tomato and spices", "Add chickpeas", "Simmer with water", "Finish with coriander"], ["Undercooked masala", "Dry curry"], 260, 12, 36, 6),
    recipe("in-egg-curry", "Egg Curry", "Indian", ["high_protein"], "egg", "Easy", 25, ["eggs", "onion", "tomato", "garam masala", "turmeric"], ["ginger", "garlic"], ["pan"], ["Boil and peel eggs", "Make onion tomato gravy", "Add spices", "Add halved eggs", "Simmer 10 min"], ["Hard yolks", "Watery gravy"], 280, 16, 12, 18),
    recipe("in-bhindi-masala", "Bhindi Masala", "Indian", ["vegetarian", "low_calorie"], "veg", "Easy", 25, ["okra", "onion", "tomato", "cumin", "coriander powder"], ["amchur"], ["pan"], ["Wash and dry bhindi completely", "Slice and fry until crispy", "Add onion and spices", "Add tomato", "Cook until done"], ["Slimy bhindi from moisture", "Overcooked"], 150, 4, 15, 8),
    recipe("in-pav-bhaji", "Mumbai Pav Bhaji", "Indian", ["street_food"], "veg", "Medium", 35, ["potato", "peas", "bell pepper", "pav bhaji masala", "butter"], ["pav buns"], ["tawa", "masher"], ["Boil and mash vegetables", "Cook with masala and butter", "Mash to smooth paste", "Toast pav with butter", "Serve hot"], ["Chunky bhaji", "Dry bhaji"], 400, 8, 52, 18, 3),
    recipe("in-kadhi-pakora", "Kadhi Pakora", "Indian", ["vegetarian"], "veg", "Medium", 40, ["yogurt", "gram flour", "onion", "turmeric", "fenugreek seeds"], ["green chili"], ["pot", "pan"], ["Make pakoras and fry", "Whisk yogurt with besan", "Cook kadhi 20 min stirring", "Add pakoras", "Make tadka and pour"], ["Lumpy kadhi", "Bitter taste"], 280, 10, 28, 14),
    recipe("in-masoor-dal", "Simple Masoor Dal", "Indian", ["high_protein", "quick"], "veg", "Easy", 20, ["red lentils", "onion", "tomato", "cumin", "turmeric"], ["garlic", "cilantro"], ["pot"], ["Boil lentils until soft", "Make onion tomato base", "Add spices", "Add lentils", "Make simple tadka"], ["Thick dal", "Watery"], 180, 12, 26, 4),
    recipe("in-aloo-paratha-f", "Stuffed Aloo Paratha", "Indian", ["breakfast"], "veg", "Medium", 30, ["wheat flour", "potato", "green chili", "cumin", "ghee"], ["coriander"], ["tawa", "rolling pin"], ["Knead soft dough", "Make spiced potato filling", "Stuff and roll carefully", "Cook on tawa with ghee", "Serve with curd"], ["Leaking filling", "Uneven cooking"], 320, 7, 42, 14),
]

# ============ JAPANESE (25) ============  
japanese = [
    recipe("jp-teriyaki-salmon", "Teriyaki Salmon", "Japanese", ["high_protein", "omega3"], "non-veg", "Easy", 20, ["salmon", "soy sauce", "mirin", "sugar", "ginger"], ["sesame", "scallion"], ["pan"], ["Mix teriyaki sauce", "Pat salmon dry", "Pan-fry skin side first", "Add sauce and glaze", "Serve with rice"], ["Overcooked fish", "Burnt sugar"], 380, 30, 12, 22),
    recipe("jp-miso-soup", "Classic Miso Soup", "Japanese", ["low_calorie", "healthy"], "veg", "Easy", 10, ["miso paste", "tofu", "wakame", "dashi", "scallion"], [], ["pot"], ["Heat dashi to simmer", "Add sliced tofu", "Add rehydrated wakame", "Remove from heat", "Dissolve miso and serve"], ["Boiling miso kills enzymes", "Too much miso = salty"], 60, 5, 6, 2),
    recipe("jp-gyudon", "Beef Bowl (Gyudon)", "Japanese", ["high_protein"], "non-veg", "Easy", 20, ["sliced beef", "onion", "soy sauce", "mirin", "dashi"], ["egg", "pickled ginger"], ["pan", "pot"], ["Simmer dashi with seasonings", "Add thinly sliced onion", "Add beef and cook", "Serve over rice", "Top with egg if desired"], ["Tough overcooked beef", "Too salty"], 480, 28, 55, 18),
    recipe("jp-tonkatsu", "Crispy Tonkatsu", "Japanese", ["high_protein"], "non-veg", "Medium", 30, ["pork loin", "flour", "egg", "panko", "cabbage"], ["tonkatsu sauce"], ["pan", "oil"], ["Pound pork thin", "Season and coat in flour, egg, panko", "Deep fry until golden", "Drain well", "Serve with shredded cabbage"], ["Oil not hot enough = greasy", "Uneven coating"], 520, 32, 25, 32),
    recipe("jp-yakitori", "Chicken Yakitori", "Japanese", ["high_protein", "low_carb"], "non-veg", "Easy", 20, ["chicken thigh", "soy sauce", "sake", "mirin", "sugar"], ["scallion"], ["skewers", "grill"], ["Cut chicken into cubes", "Make tare sauce", "Thread onto skewers", "Grill brushing with sauce", "Serve hot"], ["Dry chicken", "Burnt sauce"], 280, 25, 8, 16),
    recipe("jp-katsu-curry", "Katsu Curry", "Japanese", ["comfort"], "non-veg", "Medium", 40, ["pork cutlet", "japanese curry blocks", "potato", "carrot", "onion"], ["rice"], ["pot", "pan"], ["Make tonkatsu", "Simmer vegetables", "Add curry blocks", "Slice katsu", "Serve over rice with curry"], ["Watery curry", "Soggy katsu"], 650, 28, 70, 28),
    recipe("jp-takoyaki", "Takoyaki Balls", "Japanese", ["snack"], "non-veg", "Hard", 35, ["octopus", "flour", "dashi", "egg", "ginger"], ["bonito flakes", "mayo"], ["takoyaki pan"], ["Make batter", "Add pieces of octopus", "Cook and turn", "Top with sauce and bonito", "Serve hot"], ["Not round shape", "Undercooked center"], 280, 12, 30, 12, 8),
    recipe("jp-soba-cold", "Cold Soba Noodles", "Japanese", ["low_fat"], "veg", "Easy", 15, ["soba noodles", "soy sauce", "mirin", "dashi", "nori"], ["wasabi", "scallion"], ["pot"], ["Cook soba al dente", "Rinse in cold water", "Make dipping sauce", "Serve cold with sauce", "Garnish with nori"], ["Overcooked noodles", "Warm noodles"], 300, 12, 55, 3),
    recipe("jp-onigiri", "Rice Balls (Onigiri)", "Japanese", ["portable", "meal_prep"], "non-veg", "Easy", 15, ["sushi rice", "nori", "salmon", "salt"], ["umeboshi", "tuna mayo"], ["bowl", "hands"], ["Cook and season rice", "Wet hands with salt water", "Add filling to center", "Shape into triangle", "Wrap with nori"], ["Rice too hot to handle", "Crumbly rice"], 200, 8, 35, 4, 3),
    recipe("jp-tempura", "Vegetable Tempura", "Japanese", ["snack"], "veg", "Medium", 30, ["sweet potato", "green beans", "eggplant", "flour", "ice water"], ["tentsuyu sauce"], ["pot", "chopsticks"], ["Make ice cold batter", "Heat oil to 180C", "Dip and fry vegetables", "Drain well", "Serve with dipping sauce"], ["Heavy thick batter", "Oil not hot enough"], 280, 5, 35, 14),
    recipe("jp-omurice", "Omurice", "Japanese", ["comfort"], "egg", "Medium", 25, ["rice", "chicken", "ketchup", "eggs", "butter"], ["peas", "carrot"], ["pan"], ["Cook chicken rice with ketchup", "Beat eggs with cream", "Make thin omelette", "Place rice on omelette", "Fold over and flip"], ["Broken omelette", "Overcooked eggs"], 450, 20, 50, 20),
    recipe("jp-udon-kitsune", "Kitsune Udon", "Japanese", ["comfort"], "veg", "Easy", 20, ["udon noodles", "fried tofu", "dashi", "soy sauce", "mirin"], ["scallion", "kamaboko"], ["pot"], ["Simmer tofu in sweet soy", "Make udon broth", "Cook udon", "Assemble in bowl", "Top with sweet tofu"], ["Overcooked udon", "Bland broth"], 380, 15, 55, 12),
    recipe("jp-edamame", "Salted Edamame", "Japanese", ["snack", "high_protein"], "veg", "Easy", 10, ["edamame", "salt", "water"], [], ["pot"], ["Boil salted water", "Cook edamame 5 min", "Drain well", "Toss with more salt", "Serve warm or cold"], ["Overcooked = mushy", "Under-salted"], 120, 11, 8, 5),
    recipe("jp-chirashi", "Chirashi Bowl", "Japanese", ["high_protein", "omega3"], "non-veg", "Medium", 25, ["sushi rice", "assorted sashimi", "cucumber", "nori", "soy sauce"], ["wasabi", "pickled ginger"], ["pot", "bowl"], ["Make sushi rice", "Slice sashimi", "Cut vegetables", "Arrange over rice", "Serve with soy and wasabi"], ["Warm rice with raw fish", "Bad quality fish"], 420, 28, 50, 12),
    recipe("jp-tamagoyaki", "Rolled Omelette", "Japanese", ["breakfast"], "egg", "Medium", 15, ["eggs", "dashi", "soy sauce", "sugar", "oil"], [], ["tamagoyaki pan"], ["Mix eggs with seasonings", "Pour thin layer", "Roll to one end", "Repeat layers", "Cool and slice"], ["Broken layers", "Too dry"], 180, 14, 4, 12, 1),
    recipe("jp-curry-rice", "Japanese Curry Rice", "Japanese", ["comfort"], "non-veg", "Easy", 35, ["curry roux", "beef", "potato", "carrot", "onion"], ["rice"], ["pot"], ["Cut vegetables uniform size", "Brown meat", "Add water and simmer", "Add curry roux", "Cook until thick"], ["Watery curry", "Undercooked vegetables"], 550, 22, 65, 22),
    recipe("jp-ramen-basic", "Shoyu Ramen", "Japanese", ["comfort"], "non-veg", "Medium", 30, ["ramen noodles", "chicken broth", "soy sauce", "chashu pork", "egg"], ["nori", "scallion"], ["pot"], ["Prepare soft boiled egg", "Make seasoned broth", "Cook noodles", "Slice chashu", "Assemble and serve hot"], ["Overcooked noodles", "Cold broth"], 480, 25, 45, 20),
    recipe("jp-ochazuke", "Green Tea Rice", "Japanese", ["light", "comfort"], "non-veg", "Easy", 10, ["rice", "green tea", "salmon", "nori", "wasabi"], ["pickles"], ["teapot", "bowl"], ["Place rice in bowl", "Add salmon flakes", "Pour hot green tea over", "Add toppings", "Eat immediately"], ["Cold tea", "Too much liquid"], 250, 12, 40, 5),
    recipe("jp-karaage", "Chicken Karaage", "Japanese", ["high_protein"], "non-veg", "Medium", 30, ["chicken thigh", "soy sauce", "sake", "ginger", "potato starch"], ["garlic", "lemon"], ["pot", "bowl"], ["Marinate chicken 30 min", "Coat in potato starch", "Deep fry twice for crisp", "Drain well", "Serve with lemon"], ["Soggy coating", "Raw inside"], 380, 28, 15, 22),
    recipe("jp-donburi", "Oyakodon", "Japanese", ["comfort", "high_protein"], "non-veg", "Easy", 20, ["chicken", "eggs", "onion", "dashi", "soy sauce"], ["mitsuba"], ["pan", "lid"], ["Simmer onion in broth", "Add chicken and cook", "Pour beaten eggs", "Cover until just set", "Serve over rice"], ["Overcooked eggs", "Tough chicken"], 450, 28, 50, 15),
    recipe("jp-sunomono", "Cucumber Sunomono", "Japanese", ["low_calorie", "refreshing"], "veg", "Easy", 10, ["cucumber", "rice vinegar", "sugar", "salt", "sesame"], ["wakame"], ["bowl"], ["Slice cucumber thin", "Salt and drain 10 min", "Make vinegar dressing", "Toss together", "Chill before serving"], ["Watery from not draining", "Too sour"], 40, 1, 8, 1),
    recipe("jp-nikujaga", "Meat and Potato Stew", "Japanese", ["comfort"], "non-veg", "Easy", 35, ["beef", "potato", "carrot", "onion", "soy sauce"], ["sake", "mirin"], ["pot"], ["Cut vegetables", "Saute meat", "Add vegetables and broth", "Simmer 20 min", "Rest before serving"], ["Hard potatoes", "Tough meat"], 380, 20, 35, 16),
    recipe("jp-tsukemono", "Quick Pickled Vegetables", "Japanese", ["side", "low_calorie"], "veg", "Easy", 10, ["cucumber", "daikon", "salt", "rice vinegar", "sugar"], [], ["jar", "bag"], ["Slice vegetables", "Mix with salt", "Let sit 30 min", "Add vinegar and sugar", "Refrigerate"], ["Too salty", "Not crunchy"], 20, 0, 4, 0),
    recipe("jp-sukiyaki", "Beef Sukiyaki", "Japanese", ["high_protein"], "non-veg", "Medium", 30, ["sliced beef", "tofu", "napa cabbage", "soy sauce", "sugar"], ["enoki", "egg"], ["sukiyaki pot"], ["Heat pot and add fat", "Cook beef briefly", "Add vegetables and sauce", "Simmer together", "Dip in raw egg"], ["Overcooked beef", "Too sweet"], 480, 32, 25, 28),
    recipe("jp-gyoza", "Pan-fried Gyoza", "Japanese", ["snack"], "non-veg", "Medium", 35, ["pork mince", "cabbage", "gyoza wrappers", "garlic", "ginger"], ["soy sauce", "rice vinegar"], ["pan", "lid"], ["Mix filling ingredients", "Wrap and pleat gyoza", "Pan fry until golden", "Add water and steam", "Serve crispy side up"], ["Broken skin", "Not crispy"], 280, 15, 28, 12, 10),
]

# ============ CHINESE (25) ============
chinese = [
    recipe("cn-kung-pao", "Kung Pao Chicken", "Chinese", ["high_protein"], "non-veg", "Medium", 25, ["chicken", "peanuts", "dried chili", "soy sauce", "vinegar"], ["Sichuan peppercorn"], ["wok"], ["Velvet chicken in cornstarch", "Fry peanuts and set aside", "Stir-fry chicken", "Add sauce and chilies", "Toss with peanuts"], ["Tough chicken", "Burnt peanuts"], 380, 30, 15, 22),
    recipe("cn-fried-rice", "Classic Fried Rice", "Chinese", ["quick"], "egg", "Easy", 15, ["day-old rice", "eggs", "peas", "soy sauce", "scallion"], ["char siu", "shrimp"], ["wok"], ["Heat wok smoking hot", "Scramble eggs", "Add rice and break up", "Add soy sauce", "Mix in eggs and scallion"], ["Wet rice", "Low heat"], 350, 12, 52, 10),
    recipe("cn-sweet-sour-pork", "Sweet and Sour Pork", "Chinese", ["comfort"], "non-veg", "Medium", 30, ["pork", "pineapple", "bell pepper", "ketchup", "vinegar"], ["cornstarch"], ["wok", "pot"], ["Cut and batter pork", "Deep fry until crispy", "Make sweet sour sauce", "Stir-fry vegetables", "Combine all together"], ["Soggy coating", "Too sweet"], 420, 22, 35, 22),
    recipe("cn-mapo-tofu", "Mapo Tofu", "Chinese", ["high_protein", "spicy"], "non-veg", "Medium", 20, ["silken tofu", "ground pork", "doubanjiang", "Sichuan peppercorn", "garlic"], ["scallion"], ["wok"], ["Cook pork until crispy", "Add doubanjiang and garlic", "Add broth and tofu", "Simmer 5 min", "Thicken with cornstarch"], ["Broken tofu", "Not numbing enough"], 280, 18, 8, 20),
    recipe("cn-cashew-chicken", "Cashew Chicken", "Chinese", ["high_protein"], "non-veg", "Easy", 20, ["chicken breast", "cashews", "soy sauce", "hoisin", "garlic"], ["ginger", "bell pepper"], ["wok"], ["Velvet and cook chicken", "Toast cashews", "Make sauce", "Stir-fry vegetables", "Combine all"], ["Burnt cashews", "Dry chicken"], 380, 28, 18, 22),
    recipe("cn-wonton-soup", "Wonton Soup", "Chinese", ["comfort"], "non-veg", "Medium", 35, ["wonton wrappers", "pork mince", "shrimp", "ginger", "chicken broth"], ["bok choy"], ["pot", "bowl"], ["Make pork shrimp filling", "Wrap wontons", "Simmer in broth", "Add bok choy", "Garnish and serve"], ["Broken wontons", "Under-filled"], 250, 18, 25, 10),
    recipe("cn-bok-choy", "Garlic Bok Choy", "Chinese", ["low_calorie", "quick"], "veg", "Easy", 10, ["bok choy", "garlic", "soy sauce", "oil", "oyster sauce"], [], ["wok"], ["Wash and halve bok choy", "Heat wok with oil", "Add garlic until fragrant", "Add bok choy and sauce", "Stir-fry 3 min"], ["Overcooked = mushy", "Not washing properly"], 80, 3, 6, 5),
    recipe("cn-dan-dan-noodles", "Dan Dan Noodles", "Chinese", ["spicy"], "non-veg", "Medium", 25, ["egg noodles", "ground pork", "sesame paste", "chili oil", "soy sauce"], ["Sichuan peppercorn", "scallion"], ["wok", "pot"], ["Cook noodles", "Fry pork until crispy", "Make sesame sauce", "Toss noodles in sauce", "Top with pork"], ["Clumpy sauce", "Overcooked noodles"], 450, 20, 48, 24),
    recipe("cn-spring-rolls", "Crispy Spring Rolls", "Chinese", ["snack"], "veg", "Medium", 35, ["spring roll wrappers", "cabbage", "carrot", "mushroom", "soy sauce"], ["glass noodles"], ["wok", "pot"], ["Stir-fry filling and cool", "Wrap tightly", "Seal with water", "Deep fry until golden", "Drain and serve"], ["Open ends", "Soggy"], 180, 4, 22, 8, 6),
    recipe("cn-chow-mein", "Chicken Chow Mein", "Chinese", ["quick"], "non-veg", "Easy", 20, ["egg noodles", "chicken", "bean sprouts", "soy sauce", "oyster sauce"], ["cabbage", "carrot"], ["wok"], ["Cook and drain noodles", "Stir-fry chicken", "Cook vegetables", "Add noodles and sauce", "Toss together"], ["Soggy noodles", "Overloaded wok"], 420, 25, 48, 15),
    recipe("cn-orange-chicken", "Orange Chicken", "Chinese", ["comfort"], "non-veg", "Medium", 30, ["chicken thigh", "orange juice", "soy sauce", "honey", "cornstarch"], ["chili flakes", "orange zest"], ["wok", "pot"], ["Batter and fry chicken", "Make orange sauce", "Thicken sauce", "Toss chicken in sauce", "Garnish with zest"], ["Soggy coating", "Bitter orange"], 450, 28, 35, 22),
    recipe("cn-hot-pot", "Simple Hot Pot", "Chinese", ["interactive"], "non-veg", "Easy", 45, ["beef slices", "tofu", "vegetables", "chicken broth", "mushrooms"], ["seafood", "noodles"], ["hot pot"], ["Prepare all ingredients", "Heat broth in pot", "Cook items as desired", "Dip in sauces", "Enjoy communally"], ["Over-flavored broth", "Overcooking items"], 400, 30, 25, 20),
    recipe("cn-egg-drop-soup", "Egg Drop Soup", "Chinese", ["quick", "light"], "egg", "Easy", 10, ["chicken broth", "eggs", "cornstarch", "soy sauce", "scallion"], ["sesame oil"], ["pot"], ["Bring broth to simmer", "Thicken lightly", "Slowly drizzle beaten eggs", "Stir gently", "Garnish and serve"], ["Scrambled eggs not ribbons", "Too thick"], 100, 8, 6, 5),
    recipe("cn-steamed-fish", "Cantonese Steamed Fish", "Chinese", ["healthy", "omega3"], "non-veg", "Easy", 20, ["whole fish", "ginger", "scallion", "soy sauce", "oil"], ["cilantro"], ["steamer", "wok"], ["Score fish and season", "Steam 10-12 min", "Top with ginger scallion", "Pour hot soy sauce", "Drizzle smoking hot oil"], ["Oversteamed = dry", "Fish not fresh"], 250, 35, 3, 10),
    recipe("cn-char-siu", "Char Siu Pork", "Chinese", ["high_protein"], "non-veg", "Medium", 40, ["pork shoulder", "hoisin", "honey", "soy sauce", "five spice"], ["red food coloring"], ["oven", "brush"], ["Slice pork into strips", "Marinate overnight", "Roast at high temp", "Baste with honey", "Slice and serve"], ["Dry meat", "Burnt honey"], 380, 30, 20, 18),
    recipe("cn-congee", "Chicken Congee", "Chinese", ["comfort", "healing"], "non-veg", "Easy", 60, ["rice", "chicken", "ginger", "water", "salt"], ["scallion", "fried shallots"], ["pot"], ["Simmer rice with lots of water", "Add chicken and ginger", "Cook until thick", "Shred chicken", "Serve with toppings"], ["Too thick", "Undercooked rice"], 280, 18, 35, 6),
    recipe("cn-general-tso", "General Tso Chicken", "Chinese", ["comfort"], "non-veg", "Medium", 30, ["chicken thigh", "soy sauce", "hoisin", "chili", "cornstarch"], ["broccoli", "ginger"], ["wok", "pot"], ["Batter chicken pieces", "Deep fry until crispy", "Make spicy sauce", "Toss chicken in sauce", "Serve immediately"], ["Soggy coating", "Too salty"], 480, 28, 32, 25),
    recipe("cn-dumplings", "Pork Dumplings", "Chinese", ["snack"], "non-veg", "Medium", 40, ["dumpling wrappers", "pork mince", "cabbage", "ginger", "soy sauce"], ["garlic chives"], ["pot", "pan"], ["Make seasoned filling", "Wrap dumplings", "Boil or pan-fry", "Make dipping sauce", "Serve hot"], ["Open dumplings", "Dry filling"], 280, 15, 30, 12, 12),
    recipe("cn-beef-broccoli", "Beef with Broccoli", "Chinese", ["high_protein"], "non-veg", "Easy", 20, ["beef sirloin", "broccoli", "oyster sauce", "soy sauce", "garlic"], ["ginger"], ["wok"], ["Slice beef thin", "Velvet with cornstarch", "Stir-fry beef", "Cook broccoli", "Combine with sauce"], ["Tough beef", "Overcooked broccoli"], 350, 30, 12, 18),
    recipe("cn-salt-pepper-shrimp", "Salt and Pepper Shrimp", "Chinese", ["high_protein", "quick"], "non-veg", "Easy", 15, ["shrimp", "cornstarch", "salt", "white pepper", "garlic"], ["scallion", "chili"], ["wok"], ["Coat shrimp in cornstarch", "Deep fry until crispy", "Remove excess oil", "Toss with salt pepper garlic", "Serve immediately"], ["Soggy coating", "Too salty"], 220, 25, 8, 10),
    recipe("cn-scallion-pancake", "Scallion Pancakes", "Chinese", ["snack"], "veg", "Medium", 30, ["flour", "scallion", "salt", "oil", "sesame oil"], [], ["pan", "rolling pin"], ["Make hot water dough", "Rest 30 min", "Roll with oil and scallion", "Coil and re-roll", "Pan fry until golden"], ["Not flaky", "Too thick"], 250, 5, 35, 10, 4),
    recipe("cn-egg-foo-young", "Egg Foo Young", "Chinese", ["high_protein"], "egg", "Easy", 20, ["eggs", "bean sprouts", "pork", "mushrooms", "scallion"], ["gravy"], ["pan"], ["Beat eggs with fillings", "Fry as small omelettes", "Make oyster sauce gravy", "Pour gravy over", "Serve hot"], ["Broken omelettes", "Watery"], 280, 18, 8, 20),
    recipe("cn-ma-yi-shang-shu", "Ants Climbing Tree", "Chinese", ["spicy"], "non-veg", "Easy", 20, ["glass noodles", "ground pork", "doubanjiang", "soy sauce", "scallion"], ["Sichuan peppercorn"], ["wok"], ["Soak noodles", "Fry pork until crispy", "Add chili bean paste", "Add noodles and broth", "Cook until absorbed"], ["Mushy noodles", "Not spicy enough"], 320, 15, 35, 14),
    recipe("cn-lo-mein", "Vegetable Lo Mein", "Chinese", ["quick"], "veg", "Easy", 20, ["egg noodles", "cabbage", "carrot", "mushrooms", "soy sauce"], ["sesame oil"], ["wok"], ["Cook noodles al dente", "Stir-fry vegetables", "Add noodles and sauce", "Toss together", "Finish with sesame oil"], ["Soggy noodles", "Bland vegetables"], 350, 10, 52, 10),
    recipe("cn-szechuan-beef", "Szechuan Beef", "Chinese", ["high_protein", "spicy"], "non-veg", "Medium", 25, ["beef", "dried chili", "Sichuan peppercorn", "soy sauce", "celery"], ["carrot"], ["wok"], ["Slice beef thin", "Marinate with soy and cornstarch", "Stir-fry beef", "Add vegetables and chilies", "Finish with numbing peppercorn"], ["Tough beef", "Too oily"], 380, 28, 12, 22),
]

# Load existing data and extend
output_path = Path(__file__).parent.parent / "data" / "recipes_expanded.json"
with open(output_path, "r") as f:
    data = json.load(f)

data["recipes"].extend(maintenance)
data["recipes"].extend(indian)
data["recipes"].extend(japanese)
data["recipes"].extend(chinese)

print(f"Added {len(maintenance)} maintenance recipes")
print(f"Added {len(indian)} Indian recipes")
print(f"Added {len(japanese)} Japanese recipes")
print(f"Added {len(chinese)} Chinese recipes")
print(f"Total recipes: {len(data['recipes'])}")

with open(output_path, "w") as f:
    json.dump(data, f, indent=2)
print(f"Updated {output_path}")
