"""
Part 3: Italian, Mexican, Thai recipes
"""
import json
from pathlib import Path

def recipe(id, name, cuisine, tags, diet, diff, time, req_ing, opt_ing, cookware, steps, mistakes, cal, prot, carbs, fats, servings=2):
    return {"id": id, "name": name, "cuisine": cuisine, "category": "food", "fitness_tags": tags, "diet": diet, "difficulty": diff, "time_minutes": time, "required_ingredients": req_ing, "optional_ingredients": opt_ing, "cookware": cookware, "steps": steps, "common_mistakes": mistakes, "nutrition": {"calories": cal, "protein_g": prot, "carbs_g": carbs, "fats_g": fats}, "servings": servings}

italian = [
    recipe("it-carbonara", "Spaghetti Carbonara", "Italian", ["high_protein"], "egg", "Medium", 25, ["spaghetti", "eggs", "guanciale", "parmesan", "black pepper"], ["pecorino"], ["pot", "pan"], ["Cook pasta", "Fry guanciale", "Mix eggs with cheese", "Toss hot pasta with egg mix", "Add pasta water if needed"], ["Scrambled eggs", "No guanciale = no flavor"], 550, 22, 55, 28),
    recipe("it-margherita", "Pizza Margherita", "Italian", ["vegetarian"], "veg", "Medium", 30, ["pizza dough", "tomato sauce", "mozzarella", "basil", "olive oil"], [], ["oven", "pizza stone"], ["Stretch dough thin", "Add sauce and cheese", "Bake at highest temp", "Add fresh basil after", "Drizzle olive oil"], ["Thick dough", "Too much sauce"], 450, 18, 52, 18),
    recipe("it-risotto", "Mushroom Risotto", "Italian", ["vegetarian"], "veg", "Medium", 35, ["arborio rice", "mushrooms", "onion", "white wine", "parmesan"], ["butter", "thyme"], ["pot", "ladle"], ["Saute mushrooms aside", "Cook onion in butter", "Toast rice", "Add wine and broth gradually", "Finish with cheese"], ["Not stirring enough", "Adding cold broth"], 380, 10, 48, 15),
    recipe("it-lasagna", "Classic Lasagna", "Italian", ["comfort"], "non-veg", "Hard", 90, ["lasagna sheets", "ground beef", "tomato sauce", "bechamel", "mozzarella"], ["ricotta"], ["oven", "baking dish"], ["Make meat sauce", "Make bechamel", "Layer pasta sauce cheese", "Repeat layers", "Bake 45 min"], ["Dry lasagna", "Too saucy"], 520, 28, 42, 28),
    recipe("it-bruschetta", "Fresh Bruschetta", "Italian", ["appetizer"], "veg", "Easy", 15, ["baguette", "tomatoes", "garlic", "basil", "olive oil"], ["balsamic"], ["oven", "bowl"], ["Toast bread slices", "Dice tomatoes", "Mix with garlic basil oil", "Top bread with mixture", "Serve immediately"], ["Soggy bread", "Watery tomatoes"], 180, 4, 22, 8),
    recipe("it-pesto-pasta", "Basil Pesto Pasta", "Italian", ["quick"], "veg", "Easy", 20, ["pasta", "basil", "pine nuts", "parmesan", "garlic"], ["olive oil"], ["pot", "blender"], ["Cook pasta", "Blend pesto ingredients", "Reserve pasta water", "Toss pasta with pesto", "Add water to loosen"], ["Bitter basil", "Dry pasta"], 420, 14, 50, 20),
    recipe("it-caprese", "Caprese Salad", "Italian", ["low_carb"], "veg", "Easy", 10, ["tomatoes", "fresh mozzarella", "basil", "olive oil", "balsamic"], ["salt"], ["plate", "knife"], ["Slice tomatoes", "Slice mozzarella", "Alternate on plate", "Add basil leaves", "Drizzle oil and balsamic"], ["Cold cheese", "Bad tomatoes"], 280, 14, 8, 22),
    recipe("it-minestrone", "Minestrone Soup", "Italian", ["high_fiber"], "veg", "Easy", 40, ["cannellini beans", "pasta", "vegetables", "tomato", "vegetable broth"], ["parmesan rind"], ["pot"], ["Saute vegetables", "Add tomatoes and broth", "Simmer 20 min", "Add beans and pasta", "Cook until pasta done"], ["Overcooked pasta", "Under-seasoned"], 220, 10, 35, 5),
    recipe("it-osso-buco", "Osso Buco", "Italian", ["high_protein"], "non-veg", "Hard", 120, ["veal shanks", "onion", "carrot", "celery", "white wine"], ["gremolata"], ["dutch oven"], ["Brown shanks", "Saute vegetables", "Deglaze with wine", "Add broth and braise", "Make gremolata"], ["Not browning enough", "Dry meat"], 450, 42, 12, 22),
    recipe("it-tiramisu", "Classic Tiramisu", "Italian", ["dessert"], "egg", "Medium", 30, ["mascarpone", "eggs", "espresso", "ladyfingers", "cocoa"], ["rum"], ["bowl", "dish"], ["Make zabaglione with yolks", "Fold in mascarpone", "Dip ladyfingers in coffee", "Layer with cream", "Dust with cocoa"], ["Soggy ladyfingers", "Runny cream"], 380, 8, 32, 25),
    recipe("it-arrabbiata", "Penne Arrabbiata", "Italian", ["spicy"], "veg", "Easy", 20, ["penne", "tomato sauce", "garlic", "chili flakes", "olive oil"], ["parsley"], ["pot", "pan"], ["Cook pasta", "Fry garlic and chili", "Add tomato sauce", "Simmer 10 min", "Toss with pasta"], ["Bitter garlic", "Too spicy"], 350, 10, 52, 10),
    recipe("it-gnocchi", "Potato Gnocchi", "Italian", ["comfort"], "veg", "Medium", 45, ["potatoes", "flour", "egg", "salt"], ["butter", "sage"], ["pot", "board"], ["Boil and rice potatoes", "Mix with flour and egg", "Shape gnocchi", "Boil until they float", "Toss with butter sage"], ["Dense gnocchi", "Too much flour"], 320, 8, 52, 8),
    recipe("it-alfredo", "Fettuccine Alfredo", "Italian", ["comfort"], "veg", "Easy", 20, ["fettuccine", "butter", "parmesan", "cream", "garlic"], ["parsley"], ["pot", "pan"], ["Cook pasta", "Melt butter with garlic", "Add cream and cheese", "Toss with pasta", "Serve immediately"], ["Broken sauce", "Gummy pasta"], 580, 18, 52, 35),
    recipe("it-bolognese", "Spaghetti Bolognese", "Italian", ["high_protein"], "non-veg", "Medium", 60, ["spaghetti", "ground beef", "tomato paste", "onion", "carrot"], ["celery", "wine"], ["pot", "pan"], ["Saute vegetables", "Brown meat", "Add tomatoes", "Simmer 45 min", "Serve over pasta"], ["Not simmering long enough", "Dry sauce"], 520, 28, 55, 22),
    recipe("it-ciabatta-sandwich", "Italian Ciabatta Sandwich", "Italian", ["lunch"], "non-veg", "Easy", 10, ["ciabatta", "prosciutto", "mozzarella", "tomato", "basil"], ["olive oil"], ["knife"], ["Slice ciabatta", "Layer prosciutto", "Add cheese and tomato", "Top with basil", "Drizzle oil and close"], ["Soggy bread", "Too thick slices"], 420, 22, 35, 22),
    recipe("it-antipasto", "Antipasto Platter", "Italian", ["appetizer"], "non-veg", "Easy", 15, ["salami", "prosciutto", "olives", "artichokes", "cheese"], ["breadsticks"], ["platter"], ["Arrange meats", "Add cheeses", "Place olives and vegetables", "Add breadsticks", "Drizzle with oil"], ["Crowded platter", "Cold cheese"], 450, 20, 12, 38),
    recipe("it-eggplant-parm", "Eggplant Parmesan", "Italian", ["vegetarian"], "veg", "Medium", 50, ["eggplant", "tomato sauce", "mozzarella", "parmesan", "breadcrumbs"], ["basil"], ["oven", "pan"], ["Slice and salt eggplant", "Bread and fry slices", "Layer with sauce cheese", "Bake 25 min", "Rest before serving"], ["Soggy eggplant", "Not draining"], 380, 15, 28, 24),
    recipe("it-cacio-pepe", "Cacio e Pepe", "Italian", ["quick"], "veg", "Medium", 20, ["spaghetti", "pecorino", "black pepper", "pasta water"], [], ["pot", "pan"], ["Cook pasta very al dente", "Toast pepper in pan", "Mix cheese with pasta water", "Add pasta and toss", "Add more water if needed"], ["Clumpy cheese", "Not enough pepper"], 420, 16, 52, 18),
    recipe("it-focaccia", "Rosemary Focaccia", "Italian", ["bread"], "veg", "Medium", 90, ["flour", "yeast", "olive oil", "rosemary", "salt"], ["garlic"], ["oven", "baking pan"], ["Make and knead dough", "Rise 1 hour", "Press into oiled pan", "Dimple with fingers", "Top and bake"], ["Dense bread", "Not enough rise"], 280, 6, 42, 10),
    recipe("it-vitello", "Vitello Tonnato", "Italian", ["cold dish"], "non-veg", "Medium", 60, ["veal roast", "tuna", "capers", "anchovies", "mayo"], ["lemon"], ["pot", "blender"], ["Poach veal and cool", "Blend tuna sauce", "Slice veal thin", "Cover with sauce", "Garnish with capers"], ["Tough meat", "Thick sauce"], 380, 35, 5, 24),
    recipe("it-panna-cotta", "Vanilla Panna Cotta", "Italian", ["dessert"], "veg", "Easy", 20, ["cream", "sugar", "gelatin", "vanilla", "milk"], ["berries"], ["pot", "molds"], ["Bloom gelatin", "Heat cream with sugar", "Add gelatin", "Pour into molds", "Chill 4 hours"], ["Rubbery texture", "Not set"], 320, 4, 25, 24),
    recipe("it-frittata", "Vegetable Frittata", "Italian", ["high_protein"], "egg", "Easy", 25, ["eggs", "zucchini", "onion", "cheese", "olive oil"], ["herbs"], ["oven-safe pan"], ["Saute vegetables", "Beat eggs with cheese", "Pour over vegetables", "Cook until almost set", "Finish under broiler"], ["Overcooked eggs", "Stuck to pan"], 280, 18, 8, 20),
    recipe("it-primavera", "Pasta Primavera", "Italian", ["vegetarian"], "veg", "Easy", 25, ["penne", "zucchini", "bell pepper", "cherry tomatoes", "garlic"], ["parmesan", "basil"], ["pot", "pan"], ["Cook pasta", "Saute vegetables", "Add garlic and tomatoes", "Toss with pasta", "Top with cheese"], ["Overcooked vegetables", "Bland sauce"], 350, 12, 52, 10),
    recipe("it-amatriciana", "Bucatini Amatriciana", "Italian", ["spicy"], "non-veg", "Medium", 30, ["bucatini", "guanciale", "tomatoes", "pecorino", "chili"], [], ["pot", "pan"], ["Render guanciale", "Add tomatoes and chili", "Simmer 15 min", "Cook pasta", "Toss and add cheese"], ["Burnt guanciale", "Too spicy"], 480, 18, 52, 22),
    recipe("it-capellini", "Angel Hair with Garlic Oil", "Italian", ["quick"], "veg", "Easy", 15, ["capellini", "garlic", "olive oil", "chili flakes", "parsley"], ["lemon"], ["pot", "pan"], ["Cook pasta very al dente", "Slowly fry garlic in oil", "Add chili flakes", "Toss with pasta", "Finish with parsley"], ["Burnt garlic", "Clumpy pasta"], 380, 10, 50, 16),
]

mexican = [
    recipe("mx-tacos", "Carne Asada Tacos", "Mexican", ["high_protein"], "non-veg", "Medium", 30, ["flank steak", "corn tortillas", "onion", "cilantro", "lime"], ["salsa"], ["grill", "pan"], ["Marinate steak", "Grill to medium", "Rest and slice thin", "Warm tortillas", "Assemble tacos"], ["Overcooked steak", "Cold tortillas"], 380, 28, 25, 18),
    recipe("mx-guacamole", "Fresh Guacamole", "Mexican", ["healthy", "low_carb"], "veg", "Easy", 10, ["avocados", "lime", "cilantro", "onion", "salt"], ["jalapeno", "tomato"], ["bowl", "fork"], ["Mash avocados", "Add lime juice immediately", "Stir in onion and cilantro", "Season with salt", "Serve immediately"], ["Brown avocado", "Over-mashing"], 180, 2, 10, 16),
    recipe("mx-burrito-bowl", "Chicken Burrito Bowl", "Mexican", ["high_protein", "balanced"], "non-veg", "Easy", 25, ["chicken", "rice", "black beans", "corn", "salsa"], ["cheese", "sour cream"], ["pan", "pot"], ["Season and cook chicken", "Cook rice", "Heat beans with spices", "Assemble bowl", "Add toppings"], ["Dry chicken", "Bland rice"], 520, 38, 55, 16),
    recipe("mx-quesadilla", "Cheese Quesadilla", "Mexican", ["quick"], "veg", "Easy", 10, ["flour tortilla", "cheese", "butter"], ["chicken", "peppers"], ["pan"], ["Butter outside of tortilla", "Add cheese to half", "Fold and cook 2 min per side", "Cut into wedges", "Serve with salsa"], ["Burnt tortilla", "Cheese not melted"], 380, 15, 30, 22),
    recipe("mx-enchiladas", "Chicken Enchiladas", "Mexican", ["comfort"], "non-veg", "Medium", 40, ["corn tortillas", "chicken", "enchilada sauce", "cheese", "onion"], ["sour cream"], ["oven", "baking dish"], ["Cook and shred chicken", "Roll in tortillas", "Place in dish with sauce", "Top with cheese", "Bake 20 min"], ["Soggy tortillas", "Dry chicken"], 450, 28, 35, 22),
    recipe("mx-elote", "Mexican Street Corn", "Mexican", ["side"], "veg", "Easy", 15, ["corn on cob", "mayo", "cotija cheese", "chili powder", "lime"], ["cilantro"], ["grill", "brush"], ["Grill corn until charred", "Brush with mayo", "Sprinkle cheese", "Add chili and lime", "Serve hot"], ["Not charred enough", "Too much mayo"], 220, 5, 25, 12),
    recipe("mx-pozole", "Pozole Rojo", "Mexican", ["comfort"], "non-veg", "Medium", 90, ["pork", "hominy", "dried chilis", "onion", "garlic"], ["radish", "cabbage"], ["pot"], ["Toast and soak chilis", "Boil pork until tender", "Blend chili sauce", "Add hominy and sauce", "Simmer 30 min"], ["Tough meat", "Bitter chilis"], 380, 25, 30, 18),
    recipe("mx-chilaquiles", "Chilaquiles Verdes", "Mexican", ["breakfast"], "egg", "Easy", 20, ["tortilla chips", "salsa verde", "eggs", "cheese", "cream"], ["onion", "cilantro"], ["pan"], ["Heat salsa", "Add tortilla chips", "Simmer until softened", "Top with fried eggs", "Add cheese and cream"], ["Soggy chips", "Too much sauce"], 420, 18, 35, 25),
    recipe("mx-fajitas", "Sizzling Fajitas", "Mexican", ["high_protein"], "non-veg", "Easy", 25, ["chicken or beef", "bell peppers", "onion", "fajita seasoning", "tortillas"], ["lime", "guacamole"], ["cast iron", "grill"], ["Slice meat and vegetables", "Season well", "Cook on high heat", "Serve sizzling", "Wrap in tortillas"], ["Steamed not seared", "Overcrowded pan"], 420, 32, 28, 18),
    recipe("mx-carnitas", "Crispy Carnitas", "Mexican", ["high_protein"], "non-veg", "Medium", 180, ["pork shoulder", "orange", "garlic", "cumin", "oregano"], ["bay leaf"], ["dutch oven"], ["Cut pork into chunks", "Add seasonings and liquid", "Braise 3 hours", "Shred and crisp under broiler", "Serve in tacos"], ["Not crispy", "Dry meat"], 450, 35, 5, 32),
    recipe("mx-nachos", "Loaded Nachos", "Mexican", ["snack"], "non-veg", "Easy", 20, ["tortilla chips", "cheese", "ground beef", "jalapenos", "sour cream"], ["beans", "guacamole"], ["oven", "baking sheet"], ["Layer chips on sheet", "Add meat and cheese", "Bake until cheese melts", "Add toppings", "Serve immediately"], ["Soggy chips", "Uneven toppings"], 520, 22, 40, 32),
    recipe("mx-tamales", "Pork Tamales", "Mexican", ["traditional"], "non-veg", "Hard", 120, ["masa harina", "pork", "dried chilis", "corn husks", "lard"], ["cumin"], ["steamer", "pot"], ["Soak corn husks", "Make masa dough", "Make pork filling", "Spread and roll", "Steam 1 hour"], ["Dry masa", "Falling apart"], 380, 15, 32, 22),
    recipe("mx-tostadas", "Bean Tostadas", "Mexican", ["quick"], "veg", "Easy", 15, ["tostada shells", "refried beans", "lettuce", "cheese", "salsa"], ["avocado"], ["plate"], ["Spread beans on tostada", "Add shredded lettuce", "Top with cheese", "Add salsa", "Serve immediately"], ["Soggy tostada", "Overloaded"], 280, 10, 32, 12),
    recipe("mx-sopes", "Chorizo Sopes", "Mexican", ["traditional"], "non-veg", "Medium", 35, ["masa harina", "chorizo", "beans", "lettuce", "cheese"], ["cream"], ["griddle", "pan"], ["Make thick masa discs", "Cook and pinch edges", "Cook chorizo", "Top with beans and chorizo", "Add toppings"], ["Thin sopes", "Crumbly masa"], 380, 18, 35, 20),
    recipe("mx-torta", "Torta Ahogada", "Mexican", ["sandwich"], "non-veg", "Medium", 30, ["birote bread", "carnitas", "refried beans", "tomato sauce", "onion"], ["lime"], ["pot", "pan"], ["Make spicy tomato sauce", "Toast bread", "Fill with beans and meat", "Drown in sauce", "Serve with onion"], ["Soggy bread", "Not spicy enough"], 480, 28, 45, 22),
    recipe("mx-molcajete", "Molcajete Salsa", "Mexican", ["appetizer"], "veg", "Easy", 15, ["tomatoes", "chilis", "garlic", "cilantro", "lime"], ["onion"], ["molcajete"], ["Char tomatoes and chilis", "Grind garlic and salt", "Add charred vegetables", "Mash to desired texture", "Add lime and cilantro"], ["Too smooth", "Bitter burnt chilis"], 60, 2, 12, 1),
    recipe("mx-churros", "Cinnamon Churros", "Mexican", ["dessert"], "veg", "Medium", 30, ["flour", "butter", "eggs", "sugar", "cinnamon"], ["chocolate sauce"], ["pot", "piping bag"], ["Make choux dough", "Pipe into hot oil", "Fry until golden", "Roll in cinnamon sugar", "Serve with chocolate"], ["Soft churros", "Oil not hot enough"], 280, 4, 35, 14, 6),
    recipe("mx-birria", "Birria Tacos", "Mexican", ["high_protein"], "non-veg", "Hard", 180, ["beef chuck", "dried chilis", "onion", "garlic", "oregano"], ["consomme"], ["dutch oven"], ["Toast and soak chilis", "Blend with spices", "Braise beef 3 hours", "Shred meat", "Serve with consomme"], ["Tough meat", "Bland broth"], 420, 35, 15, 25),
    recipe("mx-ceviche", "Shrimp Ceviche", "Mexican", ["healthy", "low_carb"], "non-veg", "Easy", 30, ["shrimp", "lime juice", "tomato", "onion", "cilantro"], ["avocado", "jalapeno"], ["bowl"], ["Cook shrimp and cool", "Dice vegetables", "Mix with lime juice", "Chill 30 min", "Serve with chips"], ["Raw shrimp", "Too much lime"], 180, 22, 10, 4),
    recipe("mx-mexican-rice", "Mexican Red Rice", "Mexican", ["side"], "veg", "Easy", 30, ["rice", "tomato sauce", "chicken broth", "onion", "garlic"], ["peas", "carrot"], ["pot"], ["Toast rice until golden", "Blend tomato with onion", "Add to rice", "Add broth and simmer", "Fluff when done"], ["Mushy rice", "Undercooked"], 220, 5, 42, 4),
    recipe("mx-horchata", "Horchata", "Mexican", ["drink"], "veg", "Easy", 240, ["rice", "cinnamon", "sugar", "vanilla", "milk"], [], ["blender", "strainer"], ["Soak rice overnight", "Blend with cinnamon", "Strain through cheesecloth", "Add sugar and vanilla", "Serve over ice"], ["Gritty texture", "Not sweet enough"], 180, 3, 38, 3),
    recipe("mx-flautas", "Crispy Flautas", "Mexican", ["snack"], "non-veg", "Easy", 25, ["corn tortillas", "shredded chicken", "oil", "lettuce", "cream"], ["salsa"], ["pan"], ["Warm tortillas", "Fill with chicken", "Roll tightly and secure", "Fry until crispy", "Top with lettuce cream"], ["Open while frying", "Oil not hot enough"], 380, 22, 28, 20, 4),
    recipe("mx-coctel", "Shrimp Cocktail", "Mexican", ["appetizer"], "non-veg", "Easy", 20, ["shrimp", "ketchup", "lime", "avocado", "cilantro"], ["hot sauce", "onion"], ["bowl", "pot"], ["Poach shrimp", "Make cocktail sauce", "Dice avocado", "Combine all", "Serve cold"], ["Overcooked shrimp", "Watery sauce"], 220, 20, 15, 8),
    recipe("mx-sopa-tortilla", "Tortilla Soup", "Mexican", ["comfort"], "non-veg", "Medium", 35, ["chicken broth", "tomatoes", "dried chilis", "tortilla strips", "avocado"], ["cheese", "cream"], ["pot", "blender"], ["Toast and soak chilis", "Blend with tomatoes", "Simmer broth with sauce", "Fry tortilla strips", "Top bowl with garnishes"], ["Bitter chilis", "Soggy tortillas"], 280, 15, 25, 14),
    recipe("mx-albondigas", "Albondigas Soup", "Mexican", ["comfort"], "non-veg", "Medium", 45, ["ground beef", "rice", "tomatoes", "vegetables", "mint"], ["chipotle"], ["pot"], ["Mix meat with rice and herbs", "Form meatballs", "Make tomato broth", "Add meatballs", "Simmer 25 min"], ["Dense meatballs", "Bland broth"], 320, 22, 28, 14),
]

thai = [
    recipe("th-pad-thai", "Classic Pad Thai", "Thai", ["balanced"], "non-veg", "Medium", 25, ["rice noodles", "shrimp", "eggs", "bean sprouts", "peanuts"], ["tofu", "lime"], ["wok"], ["Soak noodles", "Make pad thai sauce", "Stir-fry shrimp and eggs", "Add noodles and sauce", "Top with peanuts"], ["Soggy noodles", "Too sweet"], 450, 22, 52, 18),
    recipe("th-green-curry", "Thai Green Curry", "Thai", ["spicy"], "non-veg", "Easy", 25, ["chicken", "coconut milk", "green curry paste", "thai basil", "eggplant"], ["bamboo shoots"], ["wok", "pot"], ["Cook paste in coconut cream", "Add chicken and cook", "Add vegetables and milk", "Simmer 10 min", "Finish with basil"], ["Separated coconut", "Overcooked chicken"], 420, 28, 15, 28),
    recipe("th-tom-yum", "Tom Yum Soup", "Thai", ["low_calorie", "spicy"], "non-veg", "Easy", 20, ["shrimp", "lemongrass", "galangal", "lime", "chili"], ["mushrooms", "fish sauce"], ["pot"], ["Boil aromatic broth", "Add mushrooms", "Add shrimp last 3 min", "Finish with lime juice", "Do not boil after lime"], ["Overcooked shrimp", "Boiled lime = bitter"], 150, 20, 8, 4),
    recipe("th-massaman", "Massaman Curry", "Thai", ["comfort"], "non-veg", "Medium", 60, ["beef", "potatoes", "massaman paste", "coconut milk", "peanuts"], ["tamarind"], ["pot"], ["Brown beef", "Fry paste in cream", "Add beef and potatoes", "Simmer until tender", "Add peanuts"], ["Tough beef", "Watery curry"], 520, 32, 30, 32),
    recipe("th-som-tam", "Green Papaya Salad", "Thai", ["low_calorie", "spicy"], "veg", "Easy", 15, ["green papaya", "tomatoes", "peanuts", "lime", "fish sauce"], ["dried shrimp", "chili"], ["mortar pestle"], ["Shred papaya thin", "Pound garlic and chili", "Add papaya and pound", "Add sauce and lime", "Toss with peanuts"], ["Over-pounding = mushy", "Too spicy"], 120, 4, 18, 5),
    recipe("th-basil-chicken", "Thai Basil Chicken", "Thai", ["high_protein", "quick"], "non-veg", "Easy", 15, ["ground chicken", "thai basil", "garlic", "chili", "oyster sauce"], ["soy sauce"], ["wok"], ["Heat wok until smoking", "Fry garlic and chili", "Add chicken break up", "Add sauces", "Toss with basil"], ["Steamed not fried", "Wilted basil"], 320, 28, 8, 18),
    recipe("th-satay", "Chicken Satay", "Thai", ["high_protein"], "non-veg", "Easy", 30, ["chicken thigh", "coconut milk", "turmeric", "curry powder", "peanut sauce"], ["cucumber"], ["grill", "skewers"], ["Marinate chicken", "Thread onto skewers", "Grill until charred", "Make peanut sauce", "Serve with sauce"], ["Dry chicken", "Burnt outside raw inside"], 380, 32, 12, 22),
    recipe("th-tom-kha", "Tom Kha Gai", "Thai", ["comfort"], "non-veg", "Easy", 25, ["chicken", "coconut milk", "galangal", "lemongrass", "mushrooms"], ["chili", "lime"], ["pot"], ["Simmer coconut with aromatics", "Add chicken and mushrooms", "Cook until done", "Finish with lime", "Serve hot"], ["Curdled coconut", "Overcooked chicken"], 350, 25, 10, 25),
    recipe("th-fried-rice", "Thai Fried Rice", "Thai", ["quick"], "egg", "Easy", 15, ["jasmine rice", "eggs", "garlic", "fish sauce", "lime"], ["shrimp", "scallion"], ["wok"], ["Heat wok very hot", "Fry eggs scramble", "Add rice and garlic", "Season with fish sauce", "Squeeze lime"], ["Wet rice", "Too much fish sauce"], 380, 12, 52, 12),
    recipe("th-red-curry", "Thai Red Curry", "Thai", ["spicy"], "non-veg", "Easy", 25, ["chicken", "coconut milk", "red curry paste", "bamboo shoots", "thai basil"], ["lime leaves"], ["wok"], ["Fry paste in coconut cream", "Add chicken", "Add vegetables and milk", "Simmer 10 min", "Garnish with basil"], ["Split coconut milk", "Too hot"], 400, 28, 12, 28),
    recipe("th-spring-rolls", "Thai Spring Rolls", "Thai", ["snack"], "veg", "Medium", 30, ["rice paper", "vermicelli", "lettuce", "carrot", "mint"], ["shrimp", "peanut sauce"], ["bowl"], ["Soak rice paper briefly", "Add fillings", "Roll tightly", "Make peanut sauce", "Serve fresh"], ["Torn wrappers", "Too little filling"], 180, 5, 28, 5, 4),
    recipe("th-panang", "Panang Curry", "Thai", ["spicy"], "non-veg", "Easy", 25, ["beef", "panang paste", "coconut milk", "lime leaves", "thai basil"], ["peanuts"], ["wok"], ["Fry paste in cream", "Add beef slices", "Add remaining coconut", "Simmer until tender", "Garnish with basil"], ["Tough beef", "Separated sauce"], 450, 30, 10, 32),
    recipe("th-pad-see-ew", "Pad See Ew", "Thai", ["comfort"], "egg", "Easy", 15, ["wide rice noodles", "chicken", "chinese broccoli", "soy sauce", "eggs"], ["garlic"], ["wok"], ["Cook noodles until charred", "Cook chicken separately", "Add vegetables", "Make well for egg", "Toss all together"], ["Not charred wok hei", "Soggy noodles"], 420, 25, 48, 16),
    recipe("th-larb", "Larb Gai", "Thai", ["high_protein", "low_carb"], "non-veg", "Easy", 15, ["ground chicken", "lime", "fish sauce", "rice powder", "mint"], ["shallot", "chili"], ["pan"], ["Cook chicken breaking up", "Toast rice and grind", "Mix with lime fish sauce", "Add herbs and rice powder", "Serve with lettuce"], ["Overcooked chicken", "Missing rice powder"], 220, 28, 5, 10),
    recipe("th-sticky-mango", "Mango Sticky Rice", "Thai", ["dessert"], "veg", "Easy", 40, ["sticky rice", "coconut milk", "mango", "sugar", "salt"], ["sesame"], ["steamer"], ["Soak and steam rice", "Make coconut sauce", "Mix rice with sauce", "Slice ripe mango", "Serve together"], ["Hard rice", "Unripe mango"], 350, 4, 65, 10),
    recipe("th-drunken-noodles", "Drunken Noodles", "Thai", ["spicy"], "non-veg", "Medium", 20, ["wide rice noodles", "chicken", "thai basil", "chili", "oyster sauce"], ["bell pepper"], ["wok"], ["Soak noodles", "Cook chicken", "Add vegetables", "Add noodles and sauce", "Toss with basil"], ["Broken noodles", "Not spicy enough"], 450, 25, 52, 15),
    recipe("th-yellow-curry", "Thai Yellow Curry", "Thai", ["mild"], "non-veg", "Easy", 30, ["chicken", "potatoes", "yellow curry paste", "coconut milk", "onion"], ["peanuts"], ["pot"], ["Fry paste until fragrant", "Add chicken and cook", "Add vegetables and coconut", "Simmer 20 min", "Serve with rice"], ["Undercooked potatoes", "Too oily"], 420, 28, 28, 25),
    recipe("th-glass-noodles", "Glass Noodle Salad", "Thai", ["low_calorie"], "non-veg", "Easy", 15, ["glass noodles", "shrimp", "lime", "fish sauce", "chili"], ["celery", "peanuts"], ["pot", "bowl"], ["Cook and cool noodles", "Poach shrimp", "Make dressing", "Toss all together", "Add herbs and nuts"], ["Clumpy noodles", "Over-dressed"], 200, 18, 22, 4),
    recipe("th-crying-tiger", "Crying Tiger Beef", "Thai", ["high_protein"], "non-veg", "Easy", 20, ["ribeye steak", "fish sauce", "lime", "chili", "rice powder"], ["shallot"], ["grill"], ["Grill steak medium rare", "Rest and slice thin", "Make spicy dipping sauce", "Toast and grind rice", "Serve with sauce"], ["Overcooked steak", "Missing sauce"], 380, 35, 5, 24),
    recipe("th-coconut-soup", "Coconut Ginger Soup", "Thai", ["healthy"], "veg", "Easy", 20, ["coconut milk", "ginger", "lemongrass", "mushrooms", "lime"], ["tofu"], ["pot"], ["Simmer coconut with ginger", "Add lemongrass", "Add mushrooms", "Season with lime", "Serve hot"], ["Too thick", "Overpowering ginger"], 250, 5, 10, 22),
    recipe("th-pineapple-rice", "Pineapple Fried Rice", "Thai", ["sweet savory"], "non-veg", "Easy", 20, ["jasmine rice", "pineapple", "shrimp", "cashews", "curry powder"], ["raisins"], ["wok"], ["Stir-fry shrimp", "Add rice and curry", "Add pineapple chunks", "Toss with cashews", "Serve in pineapple half"], ["Soggy rice", "Too sweet"], 420, 18, 58, 15),
    recipe("th-khao-soi", "Khao Soi", "Thai", ["comfort"], "non-veg", "Medium", 35, ["egg noodles", "chicken legs", "coconut milk", "khao soi paste", "shallots"], ["lime", "pickled cabbage"], ["pot"], ["Fry paste in oil", "Add coconut and broth", "Add chicken and simmer", "Cook noodles", "Garnish and serve"], ["Thin broth", "Tough chicken"], 520, 32, 42, 28),
    recipe("th-kai-jeow", "Thai Omelette", "Thai", ["quick", "comfort"], "egg", "Easy", 10, ["eggs", "fish sauce", "oil", "white pepper", "scallion"], ["ground pork"], ["wok"], ["Beat eggs with fish sauce", "Heat lots of oil very hot", "Pour eggs and let puff", "Fold and serve over rice", "Works with wok only"], ["Not puffy", "Too little oil"], 320, 14, 2, 28),
    recipe("th-rad-na", "Rad Na", "Thai", ["comfort"], "non-veg", "Medium", 25, ["wide rice noodles", "chinese broccoli", "pork", "soy sauce", "cornstarch"], ["garlic"], ["wok"], ["Char noodles in wok", "Make gravy with pork", "Thicken with cornstarch", "Pour over noodles", "Serve with chili vinegar"], ["No wok hei", "Thin gravy"], 450, 25, 50, 18),
    recipe("th-moo-ping", "Thai Grilled Pork", "Thai", ["high_protein"], "non-veg", "Easy", 30, ["pork shoulder", "coconut milk", "garlic", "fish sauce", "sugar"], ["sticky rice"], ["grill", "skewers"], ["Slice pork thin", "Marinate 1 hour", "Thread onto skewers", "Grill until charred", "Serve with sticky rice"], ["Dry meat", "Not charred"], 380, 28, 10, 25),
]

output_path = Path(__file__).parent.parent / "data" / "recipes_expanded.json"
with open(output_path, "r") as f:
    data = json.load(f)

data["recipes"].extend(italian)
data["recipes"].extend(mexican)
data["recipes"].extend(thai)

print(f"Added {len(italian)} Italian + {len(mexican)} Mexican + {len(thai)} Thai = {len(italian)+len(mexican)+len(thai)}")
print(f"Total recipes: {len(data['recipes'])}")

with open(output_path, "w") as f:
    json.dump(data, f, indent=2)
