"""
Part 4: Global recipes and all drinks
"""
import json
from pathlib import Path

def recipe(id, name, cuisine, tags, diet, diff, time, req_ing, opt_ing, cookware, steps, mistakes, cal, prot, carbs, fats, servings=2):
    return {"id": id, "name": name, "cuisine": cuisine, "category": "food", "fitness_tags": tags, "diet": diet, "difficulty": diff, "time_minutes": time, "required_ingredients": req_ing, "optional_ingredients": opt_ing, "cookware": cookware, "steps": steps, "common_mistakes": mistakes, "nutrition": {"calories": cal, "protein_g": prot, "carbs_g": carbs, "fats_g": fats}, "servings": servings}

def drink(id, name, cat, diet, time, req_ing, opt_ing, steps, size, note, cal, prot, carbs, fats):
    return {"id": id, "name": name, "category": cat, "diet": diet, "time_minutes": time, "required_ingredients": req_ing, "optional_ingredients": opt_ing, "steps": steps, "serving_size": size, "health_note": note, "nutrition": {"calories": cal, "protein_g": prot, "carbs_g": carbs, "fats_g": fats}}

global_recipes = [
    recipe("gl-avocado-toast", "Avocado Toast", "Global", ["healthy", "quick"], "veg", "Easy", 10, ["bread", "avocado", "lemon", "salt", "olive oil"], ["chili flakes", "egg"], ["toaster"], ["Toast bread", "Mash avocado with lemon", "Spread on toast", "Season with salt", "Top as desired"], ["Brown avocado", "Soggy bread"], 280, 6, 28, 18),
    recipe("gl-smoothie-bowl", "Berry Smoothie Bowl", "Global", ["healthy", "breakfast"], "veg", "Easy", 10, ["frozen berries", "banana", "yogurt", "granola", "honey"], ["chia seeds"], ["blender"], ["Blend berries and banana", "Keep thick", "Pour in bowl", "Add toppings", "Serve immediately"], ["Too thin", "Warm from blending"], 320, 8, 52, 8),
    recipe("gl-pancakes", "Fluffy Pancakes", "Global", ["breakfast", "comfort"], "egg", "Easy", 20, ["flour", "eggs", "milk", "baking powder", "butter"], ["maple syrup", "berries"], ["pan", "bowl"], ["Mix dry ingredients", "Add wet ingredients", "Don't overmix", "Cook on medium heat", "Flip when bubbly"], ["Overmixing = tough", "Too hot = burnt"], 380, 10, 50, 14),
    recipe("gl-caesar-salad", "Caesar Salad", "Global", ["low_carb"], "egg", "Easy", 15, ["romaine", "parmesan", "croutons", "caesar dressing", "lemon"], ["chicken", "anchovies"], ["bowl"], ["Wash and chop romaine", "Make or use dressing", "Toss with cheese", "Add croutons last", "Squeeze lemon"], ["Soggy croutons", "Over-dressed"], 280, 8, 15, 20),
    recipe("gl-grilled-cheese", "Grilled Cheese Sandwich", "Global", ["comfort", "quick"], "veg", "Easy", 10, ["bread", "cheese", "butter"], ["tomato", "bacon"], ["pan"], ["Butter bread outsides", "Add cheese between", "Cook on medium", "Flip when golden", "Cut diagonally"], ["Too hot = burnt", "Cheese not melted"], 420, 15, 30, 28),
    recipe("gl-hummus-plate", "Hummus Plate", "Global", ["healthy", "veg"], "veg", "Easy", 10, ["hummus", "pita", "cucumber", "tomato", "olive oil"], ["olives", "feta"], ["plate"], ["Spread hummus on plate", "Drizzle olive oil", "Cut vegetables", "Warm pita bread", "Arrange and serve"], ["Dry hummus", "Cold pita"], 320, 10, 35, 16),
    recipe("gl-french-toast", "French Toast", "Global", ["breakfast", "comfort"], "egg", "Easy", 15, ["bread", "eggs", "milk", "cinnamon", "butter"], ["maple syrup", "berries"], ["pan", "bowl"], ["Mix eggs milk cinnamon", "Dip bread slices", "Cook in butter", "Flip when golden", "Serve with toppings"], ["Soggy inside", "Too much heat"], 380, 12, 42, 18),
    recipe("gl-overnight-oats", "Overnight Oats", "Global", ["healthy", "meal_prep"], "veg", "Easy", 5, ["oats", "milk", "yogurt", "honey", "berries"], ["chia seeds", "nuts"], ["jar"], ["Combine oats and milk", "Add yogurt and honey", "Mix well", "Refrigerate overnight", "Add toppings morning"], ["Too thick", "Too runny"], 320, 12, 48, 8),
    recipe("gl-shakshuka-g", "Shakshuka", "Global", ["high_protein"], "egg", "Easy", 25, ["eggs", "tomatoes", "onion", "bell pepper", "cumin"], ["feta", "cilantro"], ["pan", "lid"], ["Saute vegetables", "Add spiced tomatoes", "Make wells for eggs", "Cover and cook", "Serve with bread"], ["Overcooked eggs", "Thin sauce"], 280, 14, 18, 16),
    recipe("gl-buddha-bowl", "Rainbow Buddha Bowl", "Global", ["healthy", "balanced"], "veg", "Easy", 25, ["quinoa", "chickpeas", "avocado", "sweet potato", "tahini"], ["greens", "cucumber"], ["pot", "oven"], ["Roast sweet potato", "Cook quinoa", "Prep vegetables", "Arrange in bowl", "Drizzle tahini"], ["Undercooked sweet potato", "Dry quinoa"], 450, 15, 55, 18),
    recipe("gl-fish-chips", "Fish and Chips", "Global", ["comfort"], "non-veg", "Medium", 35, ["white fish", "potatoes", "flour", "beer", "oil"], ["tartar sauce"], ["fryer", "pot"], ["Cut and soak potatoes", "Make beer batter", "Fry chips until golden", "Fry fish pieces", "Drain and serve"], ["Soggy chips", "Heavy batter"], 650, 25, 60, 35),
    recipe("gl-protein-bowl", "High Protein Power Bowl", "Global", ["high_protein", "muscle_gain"], "non-veg", "Easy", 25, ["chicken", "brown rice", "eggs", "spinach", "avocado"], ["salsa"], ["pan", "pot"], ["Cook rice", "Grill chicken", "Cook eggs", "Wilt spinach", "Assemble bowl"], ["Dry chicken", "Overcooked eggs"], 550, 45, 45, 22),
    recipe("gl-veggie-stir-fry", "Quick Veggie Stir Fry", "Global", ["low_calorie", "quick"], "veg", "Easy", 15, ["broccoli", "bell pepper", "carrot", "soy sauce", "garlic"], ["ginger", "tofu"], ["wok"], ["Cut vegetables uniform", "Heat wok very hot", "Stir-fry garlic first", "Add vegetables", "Season and serve"], ["Overcooked vegetables", "Crowded wok"], 150, 5, 18, 6),
    recipe("gl-banana-pancakes", "2-Ingredient Banana Pancakes", "Global", ["healthy", "quick"], "egg", "Easy", 10, ["banana", "eggs"], ["cinnamon", "berries"], ["pan"], ["Mash banana well", "Mix with beaten eggs", "Add cinnamon", "Cook small pancakes", "Flip carefully"], ["Too large = fall apart", "High heat burns"], 220, 10, 28, 8),
    recipe("gl-egg-salad", "Classic Egg Salad", "Global", ["high_protein", "quick"], "egg", "Easy", 15, ["eggs", "mayo", "mustard", "celery", "salt"], ["chives", "paprika"], ["pot", "bowl"], ["Boil eggs 12 min", "Cool and peel", "Chop eggs", "Mix with mayo mustard", "Season and serve"], ["Overcooked eggs", "Too much mayo"], 280, 14, 4, 22),
    recipe("gl-tuna-melt", "Tuna Melt Sandwich", "Global", ["high_protein"], "non-veg", "Easy", 15, ["bread", "canned tuna", "cheese", "mayo", "butter"], ["onion", "tomato"], ["pan"], ["Mix tuna with mayo", "Spread on bread", "Top with cheese", "Grill until melted", "Serve hot"], ["Dry tuna", "Burnt bread"], 450, 28, 30, 26),
    recipe("gl-minestrone-g", "Hearty Minestrone", "Global", ["high_fiber"], "veg", "Easy", 40, ["beans", "pasta", "vegetables", "tomatoes", "vegetable broth"], ["parmesan"], ["pot"], ["Saute vegetables", "Add broth and tomatoes", "Simmer 20 min", "Add pasta and beans", "Cook 10 more min"], ["Overcooked pasta", "Bland broth"], 250, 12, 38, 5),
    recipe("gl-acai-bowl", "Acai Bowl", "Global", ["antioxidant", "breakfast"], "veg", "Easy", 10, ["frozen acai", "banana", "berries", "granola", "honey"], ["coconut", "chia"], ["blender"], ["Blend acai with banana", "Keep very thick", "Pour in bowl", "Add all toppings", "Eat immediately"], ["Too runny", "Warm from blending"], 380, 6, 58, 12),
    recipe("gl-blt", "Classic BLT Sandwich", "Global", ["quick"], "non-veg", "Easy", 10, ["bread", "bacon", "lettuce", "tomato", "mayo"], [], ["pan", "toaster"], ["Cook bacon crispy", "Toast bread", "Spread mayo", "Layer bacon lettuce tomato", "Close and cut"], ["Soggy from tomato", "Limp bacon"], 450, 18, 28, 30),
    recipe("gl-stuffed-peppers", "Stuffed Bell Peppers", "Global", ["balanced"], "non-veg", "Medium", 45, ["bell peppers", "ground beef", "rice", "tomato sauce", "cheese"], ["onion"], ["oven", "pan"], ["Cook rice and beef", "Mix with sauce", "Hollow peppers", "Stuff and top cheese", "Bake 30 min"], ["Undercooked peppers", "Dry filling"], 380, 22, 30, 18),
    recipe("gl-chicken-wrap", "Grilled Chicken Wrap", "Global", ["high_protein", "meal_prep"], "non-veg", "Easy", 15, ["wrap", "grilled chicken", "lettuce", "tomato", "yogurt sauce"], ["avocado"], ["plate"], ["Slice chicken", "Spread sauce on wrap", "Add fillings", "Roll tightly", "Cut in half"], ["Torn wrap", "Too thick"], 380, 32, 30, 14),
    recipe("gl-veggie-soup", "Vegetable Soup", "Global", ["low_calorie", "healthy"], "veg", "Easy", 35, ["carrot", "potato", "celery", "onion", "vegetable broth"], ["herbs", "tomato"], ["pot"], ["Dice vegetables evenly", "Saute onion first", "Add remaining vegetables", "Cover with broth", "Simmer until tender"], ["Unevenly cut", "Under-seasoned"], 120, 4, 22, 2),
    recipe("gl-protein-pancakes", "Protein Pancakes", "Global", ["high_protein", "muscle_gain"], "egg", "Easy", 15, ["oats", "eggs", "protein powder", "banana", "milk"], ["berries"], ["blender", "pan"], ["Blend all ingredients", "Heat non-stick pan", "Pour small circles", "Flip when bubbly", "Stack and serve"], ["Too thick batter", "High heat"], 380, 28, 38, 10),
    recipe("gl-quinoa-bowl", "Mediterranean Quinoa Bowl", "Global", ["balanced", "healthy"], "veg", "Easy", 25, ["quinoa", "cucumber", "tomato", "feta", "olive oil"], ["chickpeas", "olives"], ["pot", "bowl"], ["Cook quinoa and cool", "Dice vegetables", "Combine all", "Dress with oil lemon", "Crumble feta on top"], ["Warm quinoa = wilted veggies", "Over-dressed"], 380, 12, 42, 18),
    recipe("gl-salmon-bowl", "Teriyaki Salmon Bowl", "Global", ["high_protein", "omega3"], "non-veg", "Easy", 25, ["salmon", "rice", "edamame", "teriyaki sauce", "avocado"], ["sesame", "nori"], ["pan", "pot"], ["Cook rice", "Pan-fry salmon", "Glaze with teriyaki", "Steam edamame", "Assemble bowl"], ["Overcooked salmon", "Burnt teriyaki"], 520, 35, 50, 22),
]

drinks = [
    drink("dr-green-smoothie", "Power Green Smoothie", "healthy", "veg", 5, ["spinach", "banana", "almond milk", "peanut butter"], ["protein powder"], ["Blend spinach first", "Add banana and milk", "Add peanut butter", "Blend until smooth", "Serve immediately"], "1 glass (350ml)", "Rich in iron and potassium", 280, 10, 35, 12),
    drink("dr-berry-blast", "Berry Blast Smoothie", "healthy", "veg", 5, ["mixed berries", "yogurt", "honey", "milk"], ["chia seeds"], ["Add berries to blender", "Add yogurt and milk", "Sweeten with honey", "Blend smooth", "Serve cold"], "1 glass (300ml)", "High antioxidants", 220, 8, 38, 4),
    drink("dr-detox-green", "Green Detox Juice", "detox", "veg", 10, ["cucumber", "celery", "apple", "ginger", "lemon"], [], ["Wash all produce", "Cut into pieces", "Juice all ingredients", "Stir well", "Drink immediately"], "1 glass (300ml)", "Cleansing and hydrating", 80, 2, 18, 0),
    drink("dr-turmeric-shot", "Turmeric Wellness Shot", "detox", "veg", 5, ["turmeric", "ginger", "lemon", "black pepper", "water"], ["honey"], ["Grate turmeric and ginger", "Mix with lemon juice", "Add pinch pepper", "Add water", "Drink as shot"], "1 shot (60ml)", "Anti-inflammatory boost", 20, 0, 4, 0),
    drink("dr-pre-workout", "Natural Pre-Workout", "energy", "veg", 5, ["coffee", "banana", "cocoa", "almond milk", "honey"], [], ["Brew coffee and cool", "Blend with banana", "Add cocoa and milk", "Sweeten with honey", "Drink 30 min before workout"], "1 glass (350ml)", "Natural energy boost", 180, 4, 32, 5),
    drink("dr-beet-juice", "Beet Power Juice", "energy", "veg", 10, ["beets", "apple", "carrot", "ginger", "lemon"], [], ["Peel beets", "Cut all produce", "Juice everything", "Stir well", "Drink fresh"], "1 glass (300ml)", "Improves blood flow and endurance", 140, 3, 32, 0),
    drink("dr-electrolyte", "Natural Electrolyte Drink", "energy", "veg", 5, ["coconut water", "orange", "salt", "honey", "lemon"], [], ["Squeeze citrus", "Mix with coconut water", "Add honey and salt", "Stir well", "Serve cold"], "1 glass (400ml)", "Natural sports drink alternative", 120, 1, 28, 0),
    drink("dr-whey-shake", "Classic Whey Protein Shake", "protein", "veg", 5, ["whey protein", "milk", "banana", "peanut butter"], ["oats"], ["Add milk to blender", "Add protein and banana", "Add peanut butter", "Blend smooth", "Drink post-workout"], "1 glass (400ml)", "30g protein for muscle recovery", 420, 32, 40, 16),
    drink("dr-mass-gainer", "Homemade Mass Gainer", "protein", "veg", 5, ["oats", "banana", "milk", "peanut butter", "honey"], ["protein powder"], ["Blend oats first", "Add all ingredients", "Blend until smooth", "Very thick shake", "Drink slowly"], "1 large glass (500ml)", "High calorie for bulking", 680, 25, 85, 28),
    drink("dr-egg-shake", "Egg White Protein Shake", "protein", "egg", 5, ["pasteurized egg whites", "banana", "vanilla", "milk", "honey"], [], ["Add egg whites to blender", "Add banana and milk", "Add vanilla and honey", "Blend completely", "Drink immediately"], "1 glass (350ml)", "Pure protein no fat", 280, 28, 30, 2),
    drink("dr-casein-shake", "Night Time Casein Shake", "protein", "veg", 5, ["casein protein", "almond milk", "berries", "almond butter"], [], ["Blend berries with milk", "Add casein powder", "Add almond butter", "Blend smooth", "Drink before bed"], "1 glass (350ml)", "Slow release protein for overnight recovery", 320, 28, 25, 14),
    drink("dr-ginger-lemon", "Ginger Lemon Water", "detox", "veg", 5, ["ginger", "lemon", "honey", "warm water"], ["mint"], ["Grate fresh ginger", "Squeeze lemon", "Mix in warm water", "Add honey to taste", "Drink on empty stomach"], "1 glass (250ml)", "Aids digestion and metabolism", 40, 0, 10, 0),
    drink("dr-cucumber-mint", "Cucumber Mint Refresher", "refreshing", "veg", 5, ["cucumber", "mint", "lime", "sparkling water", "sugar"], [], ["Muddle cucumber and mint", "Add lime juice", "Add sparkling water", "Sweeten lightly", "Serve ice cold"], "1 glass (300ml)", "Cooling and hydrating", 45, 0, 10, 0),
    drink("dr-watermelon-slush", "Watermelon Slush", "refreshing", "veg", 5, ["watermelon", "lime", "mint", "ice"], [], ["Blend frozen watermelon", "Add lime juice", "Add mint leaves", "Blend with ice", "Serve immediately"], "1 glass (350ml)", "Natural hydration", 80, 1, 20, 0),
    drink("dr-mango-lassi", "Sweet Mango Lassi", "refreshing", "veg", 5, ["mango", "yogurt", "milk", "sugar", "cardamom"], [], ["Blend mango chunks", "Add yogurt and milk", "Add sugar and cardamom", "Blend smooth", "Serve chilled"], "1 glass (300ml)", "Probiotic and refreshing", 240, 8, 45, 4),
    drink("dr-iced-matcha", "Iced Matcha Latte", "energy", "veg", 5, ["matcha powder", "milk", "honey", "ice"], ["vanilla"], ["Whisk matcha with water", "Add to glass with ice", "Pour cold milk", "Sweeten with honey", "Stir and enjoy"], "1 glass (350ml)", "Sustained energy without jitters", 150, 5, 22, 5),
    drink("dr-golden-milk", "Golden Turmeric Milk", "healthy", "veg", 10, ["turmeric", "milk", "cinnamon", "ginger", "honey"], ["black pepper"], ["Heat milk gently", "Whisk in turmeric", "Add cinnamon and ginger", "Sweeten with honey", "Drink warm"], "1 glass (250ml)", "Anti-inflammatory nightcap", 160, 8, 20, 5),
    drink("dr-abc-juice", "ABC Juice", "detox", "veg", 10, ["apple", "beetroot", "carrot"], ["ginger"], ["Wash all produce", "Cut into pieces", "Juice everything", "Mix well", "Drink fresh"], "1 glass (300ml)", "Classic detox combination", 120, 2, 28, 0),
    drink("dr-coconut-smoothie", "Tropical Coconut Smoothie", "refreshing", "veg", 5, ["coconut milk", "pineapple", "mango", "banana"], ["lime"], ["Add frozen fruit", "Pour coconut milk", "Blend until smooth", "Adjust thickness", "Serve cold"], "1 glass (350ml)", "Tropical refreshment", 280, 4, 45, 12),
    drink("dr-coffee-protein", "Coffee Protein Shake", "protein", "veg", 5, ["cold brew coffee", "protein powder", "almond milk", "banana"], ["cocoa"], ["Add cold coffee to blender", "Add protein powder", "Add banana and milk", "Blend smooth", "Drink as pre-workout"], "1 glass (400ml)", "Caffeine plus protein", 280, 28, 28, 5),
    drink("dr-margarita", "Classic Margarita", "alcoholic", "veg", 5, ["tequila", "lime juice", "triple sec", "salt", "ice"], [], ["Rim glass with salt", "Shake tequila with lime", "Add triple sec", "Shake with ice", "Strain into glass"], "1 cocktail", "Drink responsibly. Alcohol content: ~20%", 200, 0, 10, 0),
    drink("dr-mojito", "Fresh Mojito", "alcoholic", "veg", 5, ["rum", "mint", "lime", "sugar", "soda water"], [], ["Muddle mint with sugar", "Add lime juice", "Add rum and ice", "Top with soda", "Stir gently"], "1 cocktail", "Drink responsibly. Alcohol content: ~15%", 180, 0, 15, 0),
    drink("dr-pina-colada", "Pina Colada", "alcoholic", "veg", 5, ["rum", "coconut cream", "pineapple juice", "ice"], [], ["Blend all ingredients", "Add ice and blend", "Pour into glass", "Garnish with pineapple", "Serve frozen"], "1 cocktail", "Drink responsibly. Alcohol content: ~12%", 320, 1, 35, 12),
    drink("dr-sangria", "Red Wine Sangria", "alcoholic", "veg", 10, ["red wine", "orange juice", "brandy", "fruit", "sugar"], [], ["Cut fruit into bowl", "Add wine and brandy", "Add juice and sugar", "Chill 2 hours", "Serve cold"], "1 glass", "Drink responsibly. Alcohol content: ~10%", 180, 0, 20, 0),
    drink("dr-moscow-mule", "Moscow Mule", "alcoholic", "veg", 5, ["vodka", "ginger beer", "lime", "ice"], ["mint"], ["Fill copper mug with ice", "Add vodka", "Squeeze lime", "Top with ginger beer", "Garnish with lime"], "1 cocktail", "Drink responsibly. Alcohol content: ~12%", 150, 0, 12, 0),
]

output_path = Path(__file__).parent.parent / "data" / "recipes_expanded.json"
with open(output_path, "r") as f:
    data = json.load(f)

data["recipes"].extend(global_recipes)
data["drinks"] = drinks

print(f"Added {len(global_recipes)} Global recipes")
print(f"Added {len(drinks)} drinks")
print(f"Total recipes: {len(data['recipes'])}")
print(f"Total drinks: {len(data['drinks'])}")

with open(output_path, "w") as f:
    json.dump(data, f, indent=2)
print("Done!")
