"""
Script to generate preloaded recipes for Cook-Mood-Food
Run this script to update recipes.json with all 295 recipes
"""
import json
from pathlib import Path

# Base recipes structure
data = {
    "recipes": [],
    "drinks": [],
    "ingredient_aliases": {
        "onion": ["onions", "pyaz", "pyaaz", "kanda"],
        "tomato": ["tomatoes", "tamatar"],
        "potato": ["potatoes", "aloo", "batata"],
        "garlic": ["lahsun", "garlic cloves"],
        "ginger": ["adrak", "ginger root"],
        "green chili": ["green chillies", "hari mirch", "green pepper"],
        "coriander": ["cilantro", "dhania", "coriander leaves"],
        "turmeric": ["haldi", "turmeric powder"],
        "cumin": ["cumin seeds", "jeera"],
        "oil": ["cooking oil", "vegetable oil", "sunflower oil"],
        "salt": ["namak", "sea salt", "table salt"],
        "egg whites": ["egg white"],
        "eggs": ["egg", "anda"],
        "chicken breast": ["chicken", "chicken meat"],
        "paneer": ["cottage cheese", "indian cheese"],
        "toor dal": ["arhar dal", "pigeon peas"],
        "moong dal": ["mung dal", "mung beans", "green gram"],
        "basmati rice": ["rice", "chawal"],
        "wheat flour": ["atta", "whole wheat flour", "flour"]
    }
}

# Helper function to create recipe
def recipe(id, name, cuisine, tags, diet, diff, time, req_ing, opt_ing, cookware, steps, mistakes, cal, prot, carbs, fats, servings=2, impact=None):
    r = {
        "id": id,
        "name": name,
        "cuisine": cuisine,
        "category": "food",
        "fitness_tags": tags,
        "diet": diet,
        "difficulty": diff,
        "time_minutes": time,
        "required_ingredients": req_ing,
        "optional_ingredients": opt_ing,
        "cookware": cookware,
        "steps": steps,
        "common_mistakes": mistakes,
        "nutrition": {"calories": cal, "protein_g": prot, "carbs_g": carbs, "fats_g": fats},
        "servings": servings
    }
    if impact:
        r["cooking_impact"] = impact
    return r

def drink(id, name, cat, diet, time, req_ing, opt_ing, steps, size, note, cal, prot, carbs, fats):
    return {
        "id": id,
        "name": name,
        "category": cat,
        "diet": diet,
        "time_minutes": time,
        "required_ingredients": req_ing,
        "optional_ingredients": opt_ing,
        "steps": steps,
        "serving_size": size,
        "health_note": note,
        "nutrition": {"calories": cal, "protein_g": prot, "carbs_g": carbs, "fats_g": fats}
    }

# ============ FAT LOSS RECIPES (25) ============
fat_loss = [
    recipe("fl-grilled-chicken-salad", "Grilled Chicken Salad", "Global", ["fat_loss", "high_protein", "low_carb"], "non-veg", "Easy", 20,
           ["chicken breast", "lettuce", "cucumber", "olive oil", "lemon"], ["tomato", "onion", "pepper"],
           ["grill pan", "bowl"], ["Season chicken with salt and pepper", "Grill for 6 min each side", "Let rest 5 min then slice", "Chop vegetables", "Combine and drizzle with olive oil and lemon"],
           ["Overcooking chicken makes it dry", "Not letting chicken rest loses juices"], 250, 35, 8, 10),
    recipe("fl-egg-white-omelette", "Egg White Veggie Omelette", "Global", ["fat_loss", "high_protein", "low_fat"], "egg", "Easy", 10,
           ["egg whites", "spinach", "mushrooms", "salt"], ["bell pepper", "onion"],
           ["non-stick pan", "spatula"], ["Whisk 4 egg whites with salt", "Heat pan with cooking spray", "Add chopped veggies and cook 2 min", "Pour egg whites and cook until set", "Fold and serve"],
           ["High heat makes eggs rubbery", "Overcooking vegetables loses nutrition"], 120, 20, 4, 2),
    recipe("fl-cucumber-salad", "Refreshing Cucumber Salad", "Global", ["fat_loss", "low_calorie"], "veg", "Easy", 10,
           ["cucumber", "yogurt", "mint", "salt"], ["cumin", "garlic"],
           ["bowl", "grater"], ["Slice cucumbers thin", "Mix yogurt with salt and cumin", "Chop mint leaves", "Combine all ingredients", "Chill before serving"],
           ["Adding too much salt draws water out", "Not draining cucumber makes salad watery"], 60, 3, 8, 2),
    recipe("fl-steamed-fish", "Lemon Herb Steamed Fish", "Global", ["fat_loss", "high_protein", "low_fat"], "non-veg", "Easy", 15,
           ["white fish fillet", "lemon", "dill", "salt"], ["garlic", "olive oil"],
           ["steamer", "plate"], ["Season fish with salt", "Place lemon slices and dill on top", "Steam for 10-12 minutes", "Check flakes easily with fork", "Serve immediately"],
           ["Oversteaming makes fish mushy", "Not enough seasoning makes it bland"], 150, 30, 2, 3),
    recipe("fl-zucchini-noodles", "Garlic Zucchini Noodles", "Italian", ["fat_loss", "low_carb", "low_calorie"], "veg", "Easy", 15,
           ["zucchini", "garlic", "olive oil", "salt"], ["chili flakes", "parmesan"],
           ["spiralizer", "pan"], ["Spiralize zucchini into noodles", "Heat olive oil with minced garlic", "Add zoodles and toss 2-3 min", "Season with salt", "Serve immediately"],
           ["Overcooking zoodles makes them mushy", "Too much oil defeats the purpose"], 80, 3, 6, 5),
    recipe("fl-turkey-lettuce-wrap", "Asian Turkey Lettuce Wraps", "Asian", ["fat_loss", "high_protein", "low_carb"], "non-veg", "Easy", 15,
           ["ground turkey", "lettuce leaves", "soy sauce", "garlic", "ginger"], ["water chestnuts", "green onion"],
           ["pan", "spatula"], ["Cook turkey in pan until browned", "Add garlic, ginger, soy sauce", "Cook 5 more minutes", "Spoon into lettuce cups", "Garnish and serve"],
           ["Overcooked turkey becomes dry", "Lettuce wilts if served too warm"], 180, 25, 5, 6),
    recipe("fl-cauliflower-rice", "Low-Carb Cauliflower Rice", "Global", ["fat_loss", "low_carb", "low_calorie"], "veg", "Easy", 15,
           ["cauliflower", "olive oil", "garlic", "salt"], ["onion", "herbs"],
           ["food processor", "pan"], ["Pulse cauliflower to rice-like texture", "Heat oil and saute garlic", "Add cauliflower rice", "Cook 5-7 min stirring often", "Season and serve"],
           ["Overcooking makes it mushy", "Too much water makes it soggy"], 50, 2, 5, 3),
    recipe("fl-shrimp-stir-fry", "Quick Shrimp Veggie Stir Fry", "Asian", ["fat_loss", "high_protein", "low_carb"], "non-veg", "Easy", 15,
           ["shrimp", "broccoli", "bell pepper", "soy sauce", "garlic"], ["ginger", "sesame oil"],
           ["wok", "spatula"], ["Clean and devein shrimp", "Heat wok on high", "Stir-fry shrimp 2 min, set aside", "Cook vegetables 3 min", "Combine and add sauce"],
           ["Overcooked shrimp turns rubbery", "Low heat steams instead of sears"], 200, 28, 10, 5),
    recipe("fl-tomato-soup", "Fresh Tomato Soup", "Global", ["fat_loss", "low_calorie"], "veg", "Easy", 25,
           ["tomatoes", "onion", "garlic", "vegetable broth", "salt"], ["basil", "olive oil"],
           ["pot", "blender"], ["Saute onion and garlic", "Add chopped tomatoes", "Pour in broth and simmer 15 min", "Blend until smooth", "Season and serve"],
           ["Not cooking tomatoes enough makes soup acidic", "Over-blending makes it foamy"], 80, 3, 12, 2),
    recipe("fl-baked-chicken-breast", "Herb Baked Chicken Breast", "Global", ["fat_loss", "high_protein", "low_fat"], "non-veg", "Easy", 30,
           ["chicken breast", "olive oil", "garlic", "Italian herbs", "salt"], ["lemon", "pepper"],
           ["baking dish", "oven"], ["Preheat oven to 200C", "Rub chicken with oil and seasonings", "Bake for 25 minutes", "Check internal temp 75C", "Rest 5 min before slicing"],
           ["Overbaking dries out the chicken", "Not resting loses juices"], 200, 35, 2, 6),
    recipe("fl-spinach-salad", "Power Spinach Salad", "Global", ["fat_loss", "low_calorie"], "veg", "Easy", 10,
           ["spinach", "strawberries", "almonds", "balsamic vinegar"], ["feta cheese", "olive oil"],
           ["bowl", "knife"], ["Wash and dry spinach", "Slice strawberries", "Toast almonds lightly", "Combine in bowl", "Drizzle with balsamic"],
           ["Wet spinach dilutes dressing", "Over-toasting almonds burns them"], 150, 5, 12, 9),
    recipe("fl-veggie-soup", "Hearty Vegetable Soup", "Global", ["fat_loss", "low_calorie"], "veg", "Easy", 30,
           ["carrot", "celery", "zucchini", "tomato", "vegetable broth"], ["onion", "herbs"],
           ["pot", "knife", "ladle"], ["Dice all vegetables", "Saute in pot with little oil", "Add broth and bring to boil", "Simmer 20 minutes", "Season to taste"],
           ["Cutting vegetables unevenly gives uneven cooking", "Overcooking vegetables loses nutrients"], 90, 4, 15, 2),
    recipe("fl-greek-yogurt-bowl", "Protein Greek Yogurt Bowl", "Global", ["fat_loss", "high_protein"], "veg", "Easy", 5,
           ["greek yogurt", "berries", "honey", "chia seeds"], ["nuts", "granola"],
           ["bowl", "spoon"], ["Add yogurt to bowl", "Top with berries", "Drizzle honey", "Sprinkle chia seeds", "Serve immediately"],
           ["Adding too much honey adds calories", "Letting sit too long makes chia gummy"], 180, 15, 20, 5),
    recipe("fl-cabbage-stir-fry", "Spiced Cabbage Stir Fry", "Indian", ["fat_loss", "low_calorie"], "veg", "Easy", 15,
           ["cabbage", "mustard seeds", "curry leaves", "green chili", "salt"], ["turmeric", "oil"],
           ["pan", "spatula"], ["Shred cabbage thin", "Heat oil with mustard seeds", "Add curry leaves and chili", "Add cabbage and stir-fry 8 min", "Season and serve"],
           ["Overcooked cabbage loses crunch", "Too much oil defeats purpose"], 60, 2, 8, 3),
    recipe("fl-grilled-vegetables", "Mixed Grilled Vegetables", "Global", ["fat_loss", "low_calorie"], "veg", "Easy", 20,
           ["zucchini", "bell pepper", "eggplant", "olive oil", "salt"], ["herbs", "balsamic"],
           ["grill pan", "tongs"], ["Slice vegetables uniformly", "Brush with olive oil", "Grill 3-4 min per side", "Season with salt and herbs", "Serve warm"],
           ["Uneven slicing gives uneven cooking", "Overcrowding pan steams vegetables"], 100, 3, 10, 6),
    recipe("fl-tuna-salad", "Light Tuna Salad", "Global", ["fat_loss", "high_protein", "low_carb"], "non-veg", "Easy", 10,
           ["canned tuna", "cucumber", "onion", "lemon juice", "salt"], ["olive oil", "lettuce"],
           ["bowl", "fork"], ["Drain tuna well", "Dice cucumber and onion", "Mix all ingredients", "Add lemon juice", "Serve on lettuce"],
           ["Too much mayo adds calories", "Not draining tuna makes salad watery"], 180, 30, 5, 5),
    recipe("fl-moong-sprouts", "Tangy Moong Sprouts Salad", "Indian", ["fat_loss", "high_protein"], "veg", "Easy", 10,
           ["moong sprouts", "onion", "tomato", "lemon", "salt"], ["green chili", "coriander"],
           ["bowl", "knife"], ["Steam sprouts lightly 5 min", "Chop onion and tomato", "Mix all together", "Add lemon juice and salt", "Garnish with coriander"],
           ["Overcooking sprouts makes them mushy", "Not steaming leaves raw taste"], 120, 8, 15, 2),
    recipe("fl-clear-veg-soup", "Asian Clear Vegetable Soup", "Asian", ["fat_loss", "low_calorie"], "veg", "Easy", 20,
           ["bok choy", "mushrooms", "tofu", "vegetable broth", "soy sauce"], ["ginger", "garlic"],
           ["pot", "ladle"], ["Bring broth to simmer", "Add sliced mushrooms and tofu", "Cook 10 minutes", "Add bok choy last 2 minutes", "Season with soy sauce"],
           ["Overcooking bok choy makes it mushy", "Too much soy sauce makes it salty"], 70, 6, 8, 2),
    recipe("fl-cucumber-raita", "Cool Cucumber Raita", "Indian", ["fat_loss", "low_calorie"], "veg", "Easy", 5,
           ["yogurt", "cucumber", "cumin powder", "salt"], ["mint", "coriander"],
           ["bowl", "grater"], ["Grate cucumber and squeeze water", "Mix with yogurt", "Add cumin and salt", "Garnish with herbs", "Chill before serving"],
           ["Not squeezing cucumber makes raita watery", "Too much cumin overpowers"], 60, 4, 8, 2),
    recipe("fl-poached-eggs", "Perfect Poached Eggs", "Global", ["fat_loss", "high_protein", "low_carb"], "egg", "Medium", 10,
           ["eggs", "vinegar", "water", "salt"], ["pepper", "herbs"],
           ["pot", "slotted spoon"], ["Bring water to gentle simmer", "Add splash of vinegar", "Create gentle whirlpool", "Crack egg into center", "Cook 3-4 min and remove"],
           ["Boiling water breaks eggs apart", "Old eggs don't hold shape well"], 140, 12, 1, 10),
    recipe("fl-bell-pepper-boats", "Stuffed Bell Pepper Boats", "Global", ["fat_loss", "high_protein", "low_carb"], "non-veg", "Medium", 35,
           ["bell peppers", "ground chicken", "tomato", "onion", "spices"], ["cheese"],
           ["baking dish", "oven", "pan"], ["Halve and seed peppers", "Cook filling in pan", "Stuff peppers with mixture", "Bake at 180C for 25 min", "Serve hot"],
           ["Underbaking leaves peppers too crunchy", "Overfilling causes spillage"], 220, 25, 12, 8),
    recipe("fl-sauteed-mushrooms", "Garlic Sauteed Mushrooms", "Global", ["fat_loss", "low_calorie", "low_carb"], "veg", "Easy", 10,
           ["mushrooms", "garlic", "olive oil", "salt", "parsley"], ["thyme", "pepper"],
           ["pan", "spatula"], ["Slice mushrooms evenly", "Heat oil with garlic", "Add mushrooms in single layer", "Cook 5-7 min without stirring", "Season and garnish"],
           ["Crowding pan steams mushrooms", "Stirring too much prevents browning"], 70, 3, 4, 5),
    recipe("fl-lemon-asparagus", "Lemon Roasted Asparagus", "Global", ["fat_loss", "low_calorie"], "veg", "Easy", 15,
           ["asparagus", "olive oil", "lemon", "salt", "garlic"], ["parmesan"],
           ["baking sheet", "oven"], ["Trim asparagus ends", "Toss with oil and garlic", "Spread on baking sheet", "Roast at 200C for 10 min", "Squeeze lemon and serve"],
           ["Overcooking makes asparagus mushy", "Thin spears cook faster than thick"], 60, 3, 5, 4),
    recipe("fl-tofu-scramble", "Spiced Tofu Scramble", "Global", ["fat_loss", "high_protein", "low_carb"], "veg", "Easy", 12,
           ["firm tofu", "turmeric", "onion", "tomato", "salt"], ["cumin", "spinach"],
           ["pan", "spatula"], ["Crumble tofu by hand", "Saute onion until soft", "Add tomato and spices", "Add tofu and cook 5 min", "Season and serve"],
           ["Not pressing tofu makes it watery", "Overcooking makes it dry"], 150, 14, 6, 8),
    recipe("fl-carrot-ginger-soup", "Carrot Ginger Soup", "Global", ["fat_loss", "low_calorie"], "veg", "Easy", 30,
           ["carrots", "ginger", "onion", "vegetable broth", "salt"], ["coconut milk", "cumin"],
           ["pot", "blender"], ["Saute onion and ginger", "Add chopped carrots and broth", "Simmer 20 minutes until soft", "Blend until smooth", "Season and serve"],
           ["Not cooking carrots enough = lumpy soup", "Too much ginger overpowers"], 90, 2, 15, 2),
]

# ============ MUSCLE GAIN RECIPES (25) ============
muscle_gain = [
    recipe("mg-chicken-rice-bowl", "Power Chicken Rice Bowl", "Global", ["muscle_gain", "high_protein"], "non-veg", "Easy", 25,
           ["chicken breast", "brown rice", "broccoli", "olive oil", "soy sauce"], ["sesame seeds", "ginger"],
           ["pan", "pot"], ["Cook rice according to package", "Slice and season chicken", "Grill or pan-fry chicken 6 min per side", "Steam broccoli 5 min", "Assemble bowl and drizzle sauce"],
           ["Overcooked chicken is dry", "Undercooked rice is hard"], 450, 40, 45, 12),
    recipe("mg-beef-stir-fry", "High Protein Beef Stir Fry", "Asian", ["muscle_gain", "high_protein"], "non-veg", "Medium", 20,
           ["beef strips", "bell peppers", "broccoli", "soy sauce", "garlic"], ["ginger", "sesame oil"],
           ["wok", "knife"], ["Slice beef against the grain", "Heat wok until smoking", "Sear beef 2 min, set aside", "Stir-fry vegetables", "Combine with sauce"],
           ["Overcrowding wok steams meat", "Cutting with grain makes beef tough"], 380, 35, 15, 18),
    recipe("mg-salmon-sweet-potato", "Baked Salmon with Sweet Potato", "Global", ["muscle_gain", "high_protein", "high_omega3"], "non-veg", "Easy", 35,
           ["salmon fillet", "sweet potato", "olive oil", "lemon", "dill"], ["garlic", "asparagus"],
           ["baking sheet", "oven"], ["Preheat oven to 200C", "Cube sweet potato and toss with oil", "Season salmon with salt and dill", "Bake together for 25 min", "Squeeze lemon before serving"],
           ["Overcooking salmon dries it out", "Uneven potato cubes cook unevenly"], 480, 35, 40, 20),
    recipe("mg-eggs-toast-avocado", "Power Eggs on Toast", "Global", ["muscle_gain", "high_protein"], "egg", "Easy", 10,
           ["eggs", "whole wheat bread", "avocado", "salt", "pepper"], ["tomato", "cheese"],
           ["pan", "toaster"], ["Toast bread slices", "Cook eggs to preference", "Mash avocado with salt", "Spread avocado on toast", "Top with eggs and season"],
           ["Overcooked eggs are rubbery", "Bread gets soggy if sits too long"], 400, 20, 30, 25),
    recipe("mg-turkey-meatballs", "Protein-Packed Turkey Meatballs", "Italian", ["muscle_gain", "high_protein"], "non-veg", "Medium", 35,
           ["ground turkey", "egg", "breadcrumbs", "parsley", "garlic"], ["parmesan", "onion"],
           ["bowl", "baking sheet", "oven"], ["Mix turkey with egg and breadcrumbs", "Add seasonings and mix well", "Form into balls", "Bake at 190C for 20 min", "Serve with sauce"],
           ["Overmixing makes meatballs tough", "Too large balls don't cook through"], 350, 35, 15, 18),
    recipe("mg-lentil-curry", "Protein Dal Curry", "Indian", ["muscle_gain", "high_protein", "vegetarian"], "veg", "Easy", 30,
           ["red lentils", "onion", "tomato", "garlic", "ginger"], ["cumin", "coriander", "turmeric"],
           ["pot", "pan"], ["Rinse lentils and cook with water", "Saute onion, garlic, ginger", "Add tomato and spices", "Add cooked lentils", "Simmer 10 minutes"],
           ["Not skimming foam gives gritty texture", "Too thick - add water"], 280, 18, 40, 5),
    recipe("mg-peanut-chicken", "Peanut Butter Chicken", "Asian", ["muscle_gain", "high_protein", "high_fat"], "non-veg", "Medium", 25,
           ["chicken thighs", "peanut butter", "soy sauce", "coconut milk", "garlic"], ["lime", "chili"],
           ["pan", "pot"], ["Brown chicken thighs 5 min per side", "Mix peanut butter, soy, coconut milk", "Pour sauce over chicken", "Simmer 15 minutes", "Serve with rice"],
           ["Chicken not browned enough = pale color", "Sauce too thick - thin with water"], 520, 40, 12, 35),
    recipe("mg-cottage-cheese-pancakes", "Protein Cottage Cheese Pancakes", "Global", ["muscle_gain", "high_protein"], "egg", "Easy", 15,
           ["cottage cheese", "eggs", "oats", "banana", "cinnamon"], ["honey", "berries"],
           ["blender", "pan"], ["Blend all ingredients until smooth", "Heat non-stick pan", "Pour batter in circles", "Cook 2-3 min per side", "Stack and serve with toppings"],
           ["Batter too thin = flat pancakes", "Too high heat burns outside"], 380, 28, 35, 12),
    recipe("mg-greek-bowl", "Greek Protein Bowl", "Mediterranean", ["muscle_gain", "high_protein"], "non-veg", "Easy", 20,
           ["ground lamb", "cucumber", "tomato", "feta", "olive oil"], ["olives", "hummus", "pita"],
           ["pan", "bowl"], ["Cook spiced lamb until browned", "Dice vegetables", "Crumble feta", "Assemble bowl with all ingredients", "Drizzle olive oil"],
           ["Not draining lamb fat makes bowl greasy", "Cold lamb is less appetizing"], 480, 32, 20, 30),
    recipe("mg-tuna-pasta", "Tuna Protein Pasta", "Italian", ["muscle_gain", "high_protein"], "non-veg", "Easy", 20,
           ["pasta", "canned tuna", "olive oil", "garlic", "parsley"], ["cherry tomatoes", "capers"],
           ["pot", "pan"], ["Cook pasta al dente", "Saute garlic in olive oil", "Add drained tuna", "Toss with pasta", "Add parsley and serve"],
           ["Overcooked pasta is mushy", "Not enough oil makes it dry"], 420, 30, 50, 12),
    recipe("mg-protein-oatmeal", "Builder's Oatmeal Bowl", "Global", ["muscle_gain", "high_protein"], "egg", "Easy", 10,
           ["oats", "egg whites", "protein powder", "banana", "almond butter"], ["cinnamon", "honey"],
           ["pot", "bowl"], ["Cook oats with water", "Stir in egg whites while hot", "Mash half the banana into oats", "Add protein powder", "Top with remaining ingredients"],
           ["Adding protein powder to boiling oats clumps", "Raw egg whites if not mixed hot enough"], 450, 35, 50, 15),
    recipe("mg-chicken-burrito-bowl", "Chicken Burrito Bowl", "Mexican", ["muscle_gain", "high_protein"], "non-veg", "Easy", 25,
           ["chicken breast", "black beans", "rice", "avocado", "salsa"], ["cheese", "sour cream"],
           ["pan", "pot"], ["Cook rice and season with lime", "Season and grill chicken", "Heat black beans", "Slice avocado", "Assemble bowl with all components"],
           ["Dry chicken ruins bowl", "Cold beans are less appetizing"], 550, 42, 55, 18),
    recipe("mg-shrimp-rice", "Garlic Butter Shrimp with Rice", "Global", ["muscle_gain", "high_protein"], "non-veg", "Easy", 20,
           ["shrimp", "butter", "garlic", "white rice", "lemon"], ["parsley", "red pepper flakes"],
           ["pan", "pot"], ["Cook rice", "Melt butter and saute garlic", "Add shrimp and cook 3 min per side", "Squeeze lemon over shrimp", "Serve over rice"],
           ["Overcooked shrimp is rubbery", "Too much garlic burns and becomes bitter"], 420, 30, 45, 14),
    recipe("mg-egg-rice", "Korean Egg Rice Bowl", "Korean", ["muscle_gain", "high_protein"], "egg", "Easy", 15,
           ["rice", "eggs", "sesame oil", "soy sauce", "green onion"], ["kim chi", "gochujang"],
           ["rice cooker", "pan"], ["Cook rice", "Fry eggs sunny side up", "Place egg on rice", "Drizzle sesame oil and soy sauce", "Garnish with green onion"],
           ["Broken yolk = no sauce effect", "Overcooked egg = no runny yolk"], 380, 18, 50, 14),
    recipe("mg-protein-smoothie-bowl", "Thick Protein Smoothie Bowl", "Global", ["muscle_gain", "high_protein"], "veg", "Easy", 5,
           ["frozen banana", "protein powder", "greek yogurt", "milk", "nut butter"], ["berries", "granola", "chia"],
           ["blender", "bowl"], ["Blend frozen banana with yogurt", "Add protein powder and minimal milk", "Blend until thick", "Pour into bowl", "Add toppings"],
           ["Too much liquid = not thick enough", "Blending too long warms it up"], 400, 35, 45, 12),
    recipe("mg-steak-vegetables", "Grilled Steak with Vegetables", "Global", ["muscle_gain", "high_protein", "high_iron"], "non-veg", "Medium", 25,
           ["ribeye steak", "asparagus", "mushrooms", "butter", "garlic"], ["rosemary", "thyme"],
           ["grill pan", "oven"], ["Bring steak to room temperature", "Season generously with salt and pepper", "Grill 4 min per side for medium", "Rest 5 minutes", "Serve with grilled vegetables"],
           ["Cold steak cooks unevenly", "Not resting steak loses juices"], 550, 45, 8, 35),
    recipe("mg-paneer-tikka", "High Protein Paneer Tikka", "Indian", ["muscle_gain", "high_protein", "vegetarian"], "veg", "Medium", 30,
           ["paneer", "yogurt", "tandoori masala", "bell peppers", "onion"], ["lemon", "cilantro"],
           ["skewers", "oven or grill"], ["Cut paneer and vegetables into cubes", "Marinate in spiced yogurt 30 min", "Thread onto skewers", "Grill or bake at 200C for 15 min", "Serve with mint chutney"],
           ["Low heat makes paneer soft not charred", "Not marinating long enough = bland"], 380, 25, 10, 28),
    recipe("mg-chickpea-curry", "Protein Chickpea Curry", "Indian", ["muscle_gain", "high_protein", "vegetarian"], "veg", "Easy", 25,
           ["chickpeas", "onion", "tomato", "garam masala", "ginger"], ["spinach", "coconut milk"],
           ["pot", "pan"], ["Saute onion, ginger, garlic", "Add tomato puree and spices", "Add chickpeas and simmer", "Add coconut milk if using", "Serve with rice"],
           ["Not cooking onions enough = raw taste", "Too thick - add water"], 320, 14, 42, 10),
    recipe("mg-tofu-stir-fry", "Crispy Tofu Stir Fry", "Asian", ["muscle_gain", "high_protein", "vegetarian"], "veg", "Medium", 25,
           ["firm tofu", "broccoli", "soy sauce", "sesame oil", "garlic"], ["ginger", "cornstarch"],
           ["pan", "paper towels"], ["Press tofu and cube", "Coat with cornstarch", "Fry until golden and crispy", "Stir-fry vegetables", "Combine with sauce"],
           ["Not pressing tofu = soft texture", "Low heat = not crispy"], 300, 20, 15, 18),
    recipe("mg-hash-eggs", "Muscle Building Hash and Eggs", "American", ["muscle_gain", "high_protein"], "egg", "Easy", 25,
           ["potatoes", "ground beef", "eggs", "onion", "bell pepper"], ["cheese", "hot sauce"],
           ["pan", "spatula"], ["Cube and cook potatoes until crispy", "Add ground beef and break up", "Add diced vegetables", "Make wells and crack eggs in", "Cover and cook until eggs set"],
           ["Not crispy potatoes = soggy hash", "Overcrowding pan = steamed not fried"], 520, 35, 35, 28),
    recipe("mg-yogurt-parfait", "Bodybuilder's Parfait", "Global", ["muscle_gain", "high_protein"], "veg", "Easy", 5,
           ["greek yogurt", "granola", "mixed nuts", "honey", "berries"], ["protein powder", "chia seeds"],
           ["glass", "spoon"], ["Layer yogurt in glass", "Add granola layer", "Add fruit layer", "Repeat layers", "Drizzle honey on top"],
           ["Adding granola too early = soggy", "Too much honey adds empty calories"], 380, 25, 45, 15),
    recipe("mg-egg-muffins", "Protein Egg Muffins", "Global", ["muscle_gain", "high_protein", "meal_prep"], "egg", "Easy", 30,
           ["eggs", "bell pepper", "spinach", "feta cheese", "salt"], ["onion", "turkey bacon"],
           ["muffin tin", "oven", "bowl"], ["Whisk eggs with salt", "Chop vegetables", "Fill muffin cups 2/3 full", "Add vegetables and cheese", "Bake at 180C for 20 min"],
           ["Overfilling cups = spillover", "Not greasing pan = stuck muffins"], 200, 14, 4, 14),
    recipe("mg-pork-chops", "Juicy Grilled Pork Chops", "Global", ["muscle_gain", "high_protein"], "non-veg", "Medium", 25,
           ["pork chops", "olive oil", "garlic", "rosemary", "salt"], ["honey", "mustard"],
           ["grill pan", "tongs"], ["Bring pork to room temperature", "Season generously", "Grill 5 min per side", "Let rest 5 minutes", "Serve with vegetables"],
           ["Overcooked pork is dry", "Not resting loses juices"], 380, 35, 2, 25),
    recipe("mg-egg-fried-rice-p", "Protein Egg Fried Rice", "Asian", ["muscle_gain", "high_protein"], "egg", "Easy", 15,
           ["day-old rice", "eggs", "green peas", "soy sauce", "sesame oil"], ["green onion", "shrimp"],
           ["wok", "spatula"], ["Heat wok until smoking", "Scramble eggs and set aside", "Add rice and stir-fry 3 min", "Add peas and soy sauce", "Combine with eggs and serve"],
           ["Fresh rice is too wet", "Low heat steams rice instead of fry"], 380, 16, 52, 12),
    recipe("mg-protein-wrap", "Chicken Protein Wrap", "Global", ["muscle_gain", "high_protein", "meal_prep"], "non-veg", "Easy", 15,
           ["whole wheat wrap", "grilled chicken", "greek yogurt", "lettuce", "tomato"], ["avocado", "cheese"],
           ["plate", "knife"], ["Slice grilled chicken", "Spread yogurt on wrap", "Add chicken and vegetables", "Roll tightly", "Cut in half and serve"],
           ["Overfilling makes wrap hard to roll", "Cold chicken is less appetizing"], 420, 38, 35, 14),
]

# Add recipes to data
data["recipes"].extend(fat_loss)
data["recipes"].extend(muscle_gain)

print(f"Added {len(fat_loss)} fat loss recipes")
print(f"Added {len(muscle_gain)} muscle gain recipes")
print(f"Total recipes so far: {len(data['recipes'])}")
print("Run Part 2 to add more recipes...")

# Save to file
output_path = Path(__file__).parent.parent / "data" / "recipes_expanded.json"
with open(output_path, "w") as f:
    json.dump(data, f, indent=2)
print(f"Saved to {output_path}")
